### ISSUE TITLE
Dua Strategy dalam 1 bot dan berganti jika di setting waktu tertentu

### ISSUE THREAD

**Issue by baruga** [Fruitfella/ROBOT-binary#110]
@Fruitfella Tolong bantu ya...
Bagaimana menggabungkan 2 strategy dalam 1 bot yang akan di lakukan bot jika misalkan =
1. strategy pertama misal BB untuk berubah mulai  jam 11 siang
2. strategy 2 misal ema untuk berubah mulai jam 11 malam
jika jam sudah menunjukan jam star jam 6 pagi maka bot akan op bersasarkan strategy 2 ( masih pola strategy 2)  dan jika sudah jam 11 siang  akan berganti menjadi pola strategy 1.

Mohon bantuannya

**Comment by Fruitfella** [comment]
untuk pengaturan waktu silahkan cek <a href="https://github.com/binary-com/binary-bot/issues/312">Time Filter</a>. dan silahkan rakit sendiri 😈
