### ISSUE TITLE
mohon bantuan

### ISSUE THREAD

**Issue by apaajadehbos** [Fruitfella/ROBOT-binary#112]
![22](https://user-images.githubusercontent.com/29007726/32149597-96763ef2-bd39-11e7-9224-c8dcf65a26a7.jpg)
Mas, saya minta tolong....gimana bikin bot ini yah dengan kondisi..
candle sekarang di 2 menit adalah merah
candle sekarang di 3 menit adalah merah
candle sekarang di 5 menit adalah merah

dan saya akan OP turun, demikian sebaliknya..
![11](https://user-images.githubusercontent.com/29007726/32149595-8df55452-bd39-11e7-8fe7-52e3d415318b.jpg)

**Comment by ubanemas** [comment]
![screenshot_56](https://user-images.githubusercontent.com/27851415/32151456-9753344a-bd4f-11e7-9b72-5ef2968d06b3.jpg)
![screenshot_55](https://user-images.githubusercontent.com/27851415/32151463-a31c56c6-bd4f-11e7-8fd7-a906805fe1a8.jpg)
COBA SEPERTI INI BROW.....
![git tf](https://user-images.githubusercontent.com/27851415/32151473-bb08f276-bd4f-11e7-927a-433e88d99325.jpg)

klo ga mau ribet ambil ini,
[TF TREND TESTIS.txt](https://github.com/Fruitfella/ROBOT-binary/files/1425744/TF.TREND.TESTIS.txt)

selanjutnya silahkan explore sendiri sesuai kebutuhan, semoga membantu.....

**Comment by ubanemas** [comment]
![screenshot_58](https://user-images.githubusercontent.com/27851415/32151811-5bea9f26-bd52-11e7-9327-4be6a76f3c82.jpg)

Memastikan aja sudah sesuai rule

**Comment by apaajadehbos** [comment]
makasih banyak, sangat membantu
