### ISSUE TITLE
please help me build my even/odd strategy on binarybot

### ISSUE THREAD

**Issue by Aloyjoe** [Fruitfella/ROBOT-binary#117]
help me  admin and Mr fruitfella to write this strategy in binarybot with martingale 
1.EVEN
2.EVEN
3.ODD
4.ODD
5.EVEN
6.EVEN
7.EVEN
8.ODD
9.ODD
10.ODD
11.EVEN
12.EVEN
13.EVEN
14.EVEN
15.ODD
16.ODD
17.ODD
18.ODD
19. Return as 1....

**Comment by Fruitfella** [comment]
i think this issue had been asked and solved sometimes ago...
could you search it first?
find it in either my github or aminmarashi's.

**Comment by Netvines** [comment]
please where exactly is the updated version of this trading software?
