### ISSUE TITLE
info bot naik/turun angka spot

### ISSUE THREAD

**Issue by karing-sidikalang** [Fruitfella/ROBOT-binary#12]
Bro ku.....bisa gak, bot binary ini dikembangkan Rise Fall itu di OP karena kenaikan/turun angka spot...misalnya di V10..

xxxx.34
xxxx.94...naik 60 poin, op naik

**Comment by Fruitfella** [comment]
apanya yg gak bisa? kok gak ngerti aku?

**Comment by Fruitfella** [comment]
ini udah ada yg tanya.
cek #9 
tinggal ganti angkanya aja

**Comment by Fruitfella** [comment]
@karing-sidikalang 
cek #9
ini udah ada yg tanya.
tinggal ganti angkanya aja. perlu diingat disini blm ada sistem "poin" jd harus pake "price".
untuk contoh diatas naiknya jadi **0.6**

**Comment by karing-sidikalang** [comment]
aku tes dulu ya bosku..
