### ISSUE TITLE
Tick Trend

### ISSUE THREAD

**Issue by valentino242** [Fruitfella/ROBOT-binary#122]
Om Suhu bisa dibantu Codingnya : 

1. Tick  1   > Tick 6        =  Signal :0
2. Tick  7   > Tick 12      =  Signal :1
3. Tick 13  > Tick 18       = Signal :2

**"Jika Signal 0 - Signal 2 Confirm =  Trend Down"**

Terimakasih OM

**Comment by ubanemas** [comment]
![screenshot_3](https://user-images.githubusercontent.com/27851415/33155831-7b131c0c-d026-11e7-8992-5f7c1c8fcbc9.jpg)

coba ini om...

**Comment by valentino242** [comment]
Siap OM @ubanemas matur thanks
