### ISSUE TITLE
a bot that loops

### ISSUE THREAD

**Issue by ian0014** [Fruitfella/ROBOT-binary#123]
hi, I would like to have a binary.com bot that loops and make similar trade when it loses a trade. thanks

**Comment by opbinbr66** [comment]
Hi @ian0014!
What strategy are you trying to use? Fruitfella's gist has a lot of examples for you, but if you want some help put the xml here and I'll help you.

Best regards,
opbinbr66

**Comment by Fruitfella** [comment]
❓

**Comment by sk94191** [comment]
if you have whats app please ping me on +91-9481310850
i have a bot to earn 300$a day running it for 20 hours with no loss at all But you should have investment of atleast 500$, or you can also email me at kala.skc@gmail.com

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
