### ISSUE TITLE
bot upgrade

### ISSUE THREAD

**Issue by godonsbank** [Fruitfella/ROBOT-binary#129]
thank you Fruitfella, pls I have been working with some of your bots and see what i got here, pls i want you to help me edit it and upgrade as a professional, here there are
[godonsbank1 .txt](https://github.com/Fruitfella/ROBOT-binary/files/1519326/godonsbank1.txt)
[godonsbank2 .txt](https://github.com/Fruitfella/ROBOT-binary/files/1519329/godonsbank2.txt)
[godonsbank3.txt](https://github.com/Fruitfella/ROBOT-binary/files/1519334/godonsbank3.txt)

**Comment by Fruitfella** [comment]
what do you want me to do with those bots?
at least, explain your analysis strategies first.

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
