### ISSUE TITLE
help bro

### ISSUE THREAD

**Issue by hendracen** [Fruitfella/ROBOT-binary#137]
tolong bro,...
saya buat bot utk analisa persentase masing masing last digit utk 25 tiks, tapi ada kendala 
tolong y bro

[digitdifferpercent.zip](https://github.com/Fruitfella/ROBOT-binary/files/1554256/digitdifferpercent.zip)

**Comment by Fruitfella** [comment]
@hendracen wah, ada issue lama yg kelupaan xD
kedorong masuk kehalaman belakang sih...
untuk persentase last digit silahkan ambil Last Digit Analyzer Ver.2.0 di #35 
udah disediakan toolsnya kok malah repot2.
