### ISSUE TITLE
Who Can Help Me Create A Candle Bot So?

### ISSUE THREAD

**Issue by theboyof8x** [Fruitfella/ROBOT-binary#142]
I have a logic like this!
@Fruitfella " Can you help me"

Who can help me create a bot?
Logic 1- 4 green candles:
- command 1: Call (if win waits 397 seconds bot continue reading candle - if loss goes to command 2)
- command 2: Put (if win wait 397 seconds bot continue reading candle - if loss goes to command 3)
- command 3: put (if win wait 397 seconds bot continue reading candle - if loss goes to command 4)
- Command 4: Call (if win waits 397 seconds bot continue reading candle - if loss goes to command 5)
- Command 5: Call (if win waits 397 seconds bot continue reading candle - if loss goes to command 6)
- Order 7: Call (if win waits 397 seconds bot continue reading candle - if loss Wait 397s switch to Logic 2)
Logic 2-4 red candles:
- command 1: Put (if win wait 397 seconds bot continue reading candle - if loss goes to command 2)
- command 2: call (if win waits 397 seconds bot continue reading candle - if loss goes to command 3)
- command 3: Call (if win wait 397 seconds bot continue reading candle - if loss goes to command 4)
- command 4: put (if win waits 397 seconds bot continue reading candle - if loss goes to command 5)
- Command 5: Put (if win wait 397 seconds bot continue reading candle - if loss goes to command 6)
- Order 7: Put (if win wait 397 seconds bot continue reading candle - if loss Wait 397s switch to Logic 1)
Will Bot Run On Logic And Loop So So?

**Comment by Fruitfella** [comment]
hello my friend, howdy?

what a weird strategy you have there...
i can't find **command 6** xP

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
