### ISSUE TITLE
Purchase Rise/Fall if current candle end up/down.

### ISSUE THREAD

**Issue by armmar4711** [Fruitfella/ROBOT-binary#148]
Please help create bot Purchase Rise on next candle if current candle end up(Candle is Green when end), Purchase Rise on next candle if current candle end low(Candle is red when end).

**Comment by valentino242** [comment]
Did you mean if current candle is Green then Purchase Rise and current candle Red purchase Fall?
Duration 1 minute ?

**Comment by armmar4711** [comment]
Yes Purchase Rise(if current is Green) or Fall(if current is red) on next candle
Yes 1M

**Comment by valentino242** [comment]
[armmar4711 Bot.zip](https://github.com/Fruitfella/ROBOT-binary/files/1605463/armmar4711.Bot.zip)

**Comment by armmar4711** [comment]
Thank you. It's work. if I want to change timeframe I need to adjust on duration and interval right?

**Comment by valentino242** [comment]
Yes
