### ISSUE TITLE
please help make bot open position every subsequent tick change

### ISSUE THREAD

**Issue by lasaidhari** [Fruitfella/ROBOT-binary#152]
please help make bot open position every subsequent tick change

**Comment by Fruitfella** [comment]
gak mudeng aq.

**Comment by alantang212s** [comment]
Mungkin gini mas.
Coba saya 

Apakah maksudnya pause tick??

Sudah pernah dibahas.

https://github.com/Fruitfella/ROBOT-binary/issues/94

buat om @fruitfella

Itu kan saya udh coba.
Tp sering geser2 om tick nya.

Trus saya coba clear cookies juga.
Tetep aja.
Tick nya geser kadang dari pause 10 tick, jadi pause 14 kadang 12 bahkan 20.

Apa bisa menampilkan list tick nya di bot, every tick sehingga ga ada tick yg kelewat.

Mohon bantuannya.

Terima kasih

**Comment by Fruitfella** [comment]
@alantang212s kalo ticknya geser2, itu berarti ada delay di after purchase.
untuk menampilkan list tick : 
![capture](https://user-images.githubusercontent.com/26277327/35480108-3a9689e6-043a-11e8-912d-7543f631fc66.PNG)
`Last tick` menampilkan 1 tick terakhir setiap kali pergerakan tick
`Tick List` menampilkan list tick (pd gbr, dibatasi hanya 10 ticks terakhir)

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
