### ISSUE TITLE
please help make bot able to open position even every change 1 tick next

### ISSUE THREAD

**Issue by lasaidhari** [Fruitfella/ROBOT-binary#153]
please help make bot able to open position event every change 1 tick next

**Comment by lasaidhari** [comment]
Here's how bots work. https://youtu.be/l66EWKkZyNQ
logic bot if final digit is odd then capital multiplied 2

Berikut cara kerja bot. https://youtu.be/l66EWKkZyNQ
logika bot jika digit akhir adalah ganjil maka modal dikali 2

**Comment by valentino242** [comment]
As I know you can't buy again if your first position isn't clear.  which mean you can only Open 1 position until the postion clear. Hope it help.

**Comment by Fruitfella** [comment]
i'm too lazy to open youtube. 😛

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
