### ISSUE TITLE
diff yang sama dan lebih

### ISSUE THREAD

**Issue by derris21** [Fruitfella/ROBOT-binary#156]
Pak mau nanya ...
analisis 10 tik sebelumnya yang sudah keluar, kemudian op tik akhir yang sudah keluar lebih banyak sebanyak 4x atau lebih? bagaimana y...
misal 
1. 10111.53 **4**
2. 10111.53 **3**
3. 10121.52 **9**
4. 10101.54 **5**
5. 10111.53 **4**
6. 10101.58 **4**
7. 10110.51 **4**
8. 10111.53 **2**
9. 10110.51 **1**
10. 10111.51 **1**
analisa : 4
[binary-bot 2018.txt](https://github.com/Fruitfella/ROBOT-binary/files/1614318/binary-bot.2018.txt)
terims

**Comment by tuliofindi** [comment]
Hello friend, could you interact with me, I need help!

**Comment by lasaidhari** [comment]
![digit difer paling banyak keluar](https://user-images.githubusercontent.com/34808023/34911726-c0f18e0c-f902-11e7-9476-e1fa4b7b5467.jpg)

**Comment by lasaidhari** [comment]
[diferrs paling banyak muncul.zip](https://github.com/Fruitfella/ROBOT-binary/files/1628919/diferrs.paling.banyak.muncul.zip)

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
