### ISSUE TITLE
Color to color dengan skip dan reset martingale

### ISSUE THREAD

**Issue by aifhinvestama** [Fruitfella/ROBOT-binary#159]
Martingale factor 1
Level 8
TF 1 min...
Rule :
Jika candle hijau (rise) maka purchase rise di awal candle selanjutnya dalam 55 detik
Jika candle merah (fall) maka purchase fall di awal candle selanjutnya dalam 55 detik
Jika candle Flat skip candle jangan ada OP

**Comment by aifhinvestama** [comment]
Mohon bantuanya suhu...
Trading hanya di awal tik...
Ato awal candle... Dan detiknya bisa diganti disesuaikan dengan time frame...

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/34901956-7f2f4522-f844-11e7-87a3-a83b4799411f.PNG)

MMnya silahkan dipasang sendiri, bisa diambil dari #35, **`new candle`** juga ada disitu.
