### ISSUE TITLE
tolong bantuannya Om masta

### ISSUE THREAD

**Issue by ltsbahar99** [Fruitfella/ROBOT-binary#167]
saya punya strategi digit over:
cara op nya seperti ini mas,:
LDP=1,
purchase Over satu jika modus lebih besar 1
mohon bantuannya mas...

**Comment by Fruitfella** [comment]
kurang jelas. itu modus, modus dari apa?

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
