### ISSUE TITLE
Contact privately

### ISSUE THREAD

**Issue by xremmy** [Fruitfella/ROBOT-binary#181]
Hello Fruitfella,
Please, i would like to send you my bot privately to help check the code. It stops trading abruptly even when its on vps.

I know you don't like sharing your mail, here is mine if you can kindly send your email there. xremmy@gmail.com

Thank you.

**Comment by Fruitfella** [comment]
@xremmy i just sent you an email with a message exactly like this : 

hi xremmy,

you can send your bot here. its late night here, so i'll check it tomorrow (or the day after tomorrow).

- fruit
