### ISSUE TITLE
To store last four digits

### ISSUE THREAD

**Issue by thehightechsol** [Fruitfella/ROBOT-binary#190]
Please can someone help me with a code to save the ticker log in excel or txt please.

I just intend to find a pattern. As it  is very time consuming to sit live and wait for the setup 
i intend to download the ticker as log  and to formulate a pattern.

Thank you

**Comment by Daler4ik** [comment]
![screenshot_1](https://user-images.githubusercontent.com/31123446/36350489-7070e68e-14ba-11e8-89cc-9098ac96884a.png)

**Comment by Daler4ik** [comment]
![screenshot_2](https://user-images.githubusercontent.com/31123446/36350507-a8597bba-14ba-11e8-919d-b980177e43ba.png)

**Comment by thehightechsol** [comment]
Thats great...thank for the help. However I didnt the last variable...can you drop the code please

**Comment by thehightechsol** [comment]
i got it : appears to be last tick thank you

**Comment by Daler4ik** [comment]
@thehightechsol , I'm glad I helped you. :)
