### ISSUE TITLE
Purchase rise as soon as the new candle that opens is green and fall as soon as red, for a duration 1min.

### ISSUE THREAD

**Issue by Gazmiche** [Fruitfella/ROBOT-binary#191]
Hi @Fruitfella @binary-ex-machina
Hi everyone, I'm new here.
I have a logic that I want to adopt to my strategy. Purchase rise as soon as the new candle that opens is green and fall as soon as red, for a duration 1min for each bet. Please help me. Thank you.

**Comment by Daler4ik** [comment]
@Gazmiche , Hi friend. Keep)
[Gazmiche.zip](https://github.com/Fruitfella/ROBOT-binary/files/1740626/Gazmiche.zip)

**Comment by Gazmiche** [comment]
Thank you @Daler4ik 
Is it possible to set the expiry time of each trade to 1min?
Because as soon as I launch the bot each trade closes in about 10s maximum, it's too fast. I want to adjust it to 1min, but I can not, is it possible? If yes, please help me.

**Comment by Daler4ik** [comment]
@Gazmiche , keep

[Gazmiche.zip](https://github.com/Fruitfella/ROBOT-binary/files/1745779/Gazmiche.zip)

**Comment by Gazmiche** [comment]
Thank you my brother. You are exceptional. Big thanks.
