### ISSUE TITLE
cara bangun bot

### ISSUE THREAD

**Issue by apaajadehbos** [Fruitfella/ROBOT-binary#20]
salam mas, sorry ganggu...saya lihat mas dari indonesia. saya bisa inta tolong mas. saya ada trik nih, setiap 4 candle sama berurutan hijau, kita purchase naik dan 4 candle merah berurutan kita purchase turun. dan dia op langsung di detik pertama candle ke 5 gitu....tolong bantu mas, gmn caranya

**Comment by Fruitfella** [comment]
![4candles](https://cloud.githubusercontent.com/assets/26277327/26529702/2771391c-43ef-11e7-9f2b-1d35fbc7deaa.PNG)

bot nya aq upload di <a href="https://gist.github.com/Fruitfella/054b0a082ec68ab8dd866c57a61b1786">sini</a>

**Comment by Fruitfella** [comment]
@apaajadehbos ini versi 2 dari bot diatas. disini purchase hanya dilakukan saat candle baru muncul.
perlu diingat bahwa pada trade binary ada jarak 1 tick dari propose contract ke entry spot. artinya pada durasi 1 menit, transaksi akan di close pada 1 menit + 1 tick. oleh karena itu transaksi berikutnya harus menunggu candle baru berikutnya. (hanya bisa 2x trade dalam 3 menit)
![4candles](https://cloud.githubusercontent.com/assets/26277327/26531291/7ff3b080-4410-11e7-8446-9a55db5d99be.PNG)
silahkan download pada link yg sama dgn diatas.

**Comment by apaajadehbos** [comment]
makasih yah, tapi saya mau tanya...bagaimana maksudnya HANYA BISA 2X TRADE DALAM 3 MENIT ?

**Comment by Fruitfella** [comment]
@apaajadehbos 
![4candles](https://cloud.githubusercontent.com/assets/26277327/26532481/f96aeabc-442b-11e7-9d96-6272680f6ff5.PNG)

**Comment by apaajadehbos** [comment]
oh...ok...makasih banyak
