### ISSUE TITLE
verify next 3candles

### ISSUE THREAD

**Issue by nramade** [Fruitfella/ROBOT-binary#200]
hello everybody
i need help on this issue if rsi reach 30 verify next 3 candles are red then purchas call in the 4th candle
the triger will be rsi level then the count of candles begin like this
![capture](https://user-images.githubusercontent.com/36540096/36933781-e9db6c62-1ed6-11e8-9811-5098cf4a10c5.JPG)
i tried with last 3candles code from fruitfella but i need to check next 3 candles not previous candles

**Comment by AlienFly** [comment]
One way to do this

![3cr](https://user-images.githubusercontent.com/36364199/36936234-3b7fe364-1f4e-11e8-8c11-026fae629b8f.png)

[3_candle_rsi.zip](https://github.com/Fruitfella/ROBOT-binary/files/1777617/3_candle_rsi.zip)

**Comment by nramade** [comment]
@AlienFly thank u i will  est and report back

**Comment by nramade** [comment]
@AlienFly it didnt purchase even if requirement meat
![capture1](https://user-images.githubusercontent.com/36540096/36937092-07a3fea6-1f06-11e8-93fb-3cf3f73a27aa.JPG)

**Comment by AlienFly** [comment]
In your example, after penetrating RSI 70 level - there were not 3 bullish candles.

![wer](https://user-images.githubusercontent.com/36364199/36937218-bc1235c4-1f5b-11e8-8cd9-0326839f719c.jpg)


And in next moment, the RSI did't drop below 70 to update the entry conditions.

**Comment by nramade** [comment]
i see but it must purchase next setup after number 3 in ur example anyway to fix that?
and thank u very much

**Comment by AlienFly** [comment]
Describe step by step the logic of input.
English is not my native language. Therefore it is desirable to be more detailed.

**Comment by nramade** [comment]
well if candles stay above 70 keep searching for 3 bullish candles if 4th candle is also bullish keep purchasing put until its won
![alien](https://user-images.githubusercontent.com/36540096/36937482-be1566c0-1f0b-11e8-9b5f-5666220bb269.jpg)

**Comment by AlienFly** [comment]
Check this. If 3 identical candles close above/below the levels of RSI - open up/down until the moment of winning.

![test](https://user-images.githubusercontent.com/36364199/36937637-22c2fa64-1f62-11e8-8d7e-c6d82256079f.png)


[3_candle_rsi.v2.zip](https://github.com/Fruitfella/ROBOT-binary/files/1777741/3_candle_rsi.v2.zip)

**Comment by nramade** [comment]
stake and initial amount are the same??

**Comment by AlienFly** [comment]
yes

**Comment by nramade** [comment]
@AlienFly thank u now its perfect
