### ISSUE TITLE
Mohon di bantu memasang run after

### ISSUE THREAD

**Issue by carlordum** [Fruitfella/ROBOT-binary#204]
![2018-03-07 12_40_03-binary bot](https://user-images.githubusercontent.com/37133792/37076158-e8392794-2207-11e8-918b-a72e1e5b4d11.jpg)
 
Hello fruit tolong di bantu, mau bikin kalau tiap x loss ada durasi atau delay , di coba menggunakan blok run after, d letakkan di blok no 4 tidak berhasil, sudah di pindah" letaknya, berhasil ada delay nya, tapi martingale nya malah tidak berfungsi.
Thank's

**Comment by Fruitfella** [comment]
![untitled](https://user-images.githubusercontent.com/26277327/37198498-15db5cd0-23b1-11e8-97fe-55d71fa164cd.png)

**Comment by carlordum** [comment]
Thank You!!!!

**Comment by komenggg** [comment]
heloe can some one help me
