### ISSUE TITLE
Mohon Bantuan Digit

### ISSUE THREAD

**Issue by carlordum** [Fruitfella/ROBOT-binary#205]
![2018-03-11 01_17_01-binary bot](https://user-images.githubusercontent.com/37133792/37245429-68896250-24ca-11e8-88c7-f501344039de.jpg)
![2018-03-11 01_17_49-binary bot](https://user-images.githubusercontent.com/37133792/37245430-68d1ed90-24ca-11e8-9b56-2c8444ffc9ef.jpg)
 Nohon dibantu @Fruitfella, bagaimana meletakkan martingale, sudah di pasang martingale tapi tidak berfungsi, 
Thanks

**Comment by Fruitfella** [comment]
maksudnya tidak berfungsi bagaimana?
itu sudah pas, mestinya itu bisa jalan.

**Comment by carlordum** [comment]
bila loss, stakes tidak melipat gandakan, seharusnya bila kalah sekali stakes di kali 10, tapi ini tetap 0.35 stakenya,

**Comment by carlordum** [comment]
wkwkwkwk, iya bro, work ternyata, kemarin mungkin uda teler pasang lego nya, uda d puter" kok ga jalan" martingale nya, hehee
Thanks
