### ISSUE TITLE
Spot Price Analyzer BOT

### ISSUE THREAD

**Issue by akh2018** [Fruitfella/ROBOT-binary#206]
Hello , i nned  to some BOT developer for make Robot from My Killer Strategies on SPOT Analyzer.
Pls update me.

Thanks you

**Comment by Daler4ik** [comment]
@akh2018 , Which developer?

**Comment by Fruitfella** [comment]
sorry dude, i only make trading robot, not killer robot. you know that killing is illegal, right?
i don't want to do anything illegal.
 xD

**Comment by akh2018** [comment]
Hello Fruitfella ,
Thanks for reply , The Killer just a name and we all know there are no any killer strategy for real aacount.
However , pls call me on : akhnetbuster@gmail.com for send you strategy and if you agree starting for BOT.
Thanks you

**Comment by Fruitfella** [comment]
@akh2018 of course i know. it was a joke xD

**Comment by akh2018** [comment]
Pls send reply  to my e-mail. thanks you
