### ISSUE TITLE
The Bot is not running

### ISSUE THREAD

**Issue by thehightechsol** [Fruitfella/ROBOT-binary#208]
The following bot should make a call or put if the last tick is above Upper BB and RSI >70 and vice versa however when i run the bot it is not working. Any suggestions
[bb_RISE_FALL.txt](https://github.com/Fruitfella/ROBOT-binary/files/1800300/bb_RISE_FALL.txt)

**Comment by AlienFly** [comment]
you need replace **"Bollinger Bands Array"** on **"Bollinger Bands"**

**Comment by thehightechsol** [comment]
ok ...thank you..
