### ISSUE TITLE
apakah kita bisa OP pada candle selanjutnya

### ISSUE THREAD

**Issue by apaajadehbos** [Fruitfella/ROBOT-binary#21]
halo mas, semoga sehat2..bisa ngembangin mas bot yang tiap OP pada candle selanjutnya itu loh..tq...

**Comment by Fruitfella** [comment]
@apaajadehbos IMPOSSIBLE, ini bukan soal bot tapi soal **contact expiry** , contract expiry itu udah ada ketentuan dari sononya, kita cuman bisa pilih doang, jd bukan kita yg ngatur.
satu2nya cara utk OP disetiap new candle itu dengan memilih Duration yg lebih kecil dari Candle Interval, tapi dgn begitu strategi kita jd sia2.
cth : pilih durasi 5-10 ticks pada candle interval 1 menit. atau durasi 1 menit pada candle interval 2 menit.

**Comment by Fruitfella** [comment]
Oops kyknya aq salah tanggap. ini bukan pertanyaan hahaha
gara2 gagal terus nyoba konek metatrader ke binary.com jd gagal fokus. _lol_
btw, congrats @apaajadehbos !
