### ISSUE TITLE
martynya kenapa gak jalan yah

### ISSUE THREAD

**Issue by karing-sidikalang** [Fruitfella/ROBOT-binary#22]
kenapa martinya gak jalan yah? saya set candle 3 berurutan, purchase refersal dia...loss 2 kali gak OP lagi dia...martynya kenapa itu yah
![rrr](https://cloud.githubusercontent.com/assets/28832596/26581647/3302e992-4570-11e7-90f6-928b8b88e573.png)

**Comment by Fruitfella** [comment]
@karing-sidikalang upload screenshot blocks mu, biar aq liat salahnya dmn, kalo cuma gambar ini aq mana tau apanya yg salah.
