### ISSUE TITLE
Mohon Bantuannya Mastah

### ISSUE THREAD

**Issue by Yusriadi78** [Fruitfella/ROBOT-binary#235]
Halo @Fruitfella

Tolong buatkan Bot Touch di Market Vol.100 dengan batasan barrier -+2 Durasi 3 Menit
dengan tambahan indikator (Hull MA periode 9) dan (Bollinger Bands periode 10 Std. Dev. Up/Down 2)

Analisanya : Pastikan Warna Candle sama
1. Candel TF 30 menit (Mengukur kekuatan Trend)
2. Candel TF 15 menit (Mengukur kekuatan Trend)
3. Candel TF 5 menit 
4. Candel TF 1 menit
5. Warna Candle harus sama
6. Candle TF 5 menit dan Candle TF 1 menit sama Warnanya Candle TF 30 dan 15 menit, jika warna Candle TF 30 dan 15 menit berbeda warna, maka analisa Open Posisi berhenti, tunggu sampai Warna Candle TF 30 dan 15 menit sama untuk lanjut menganalsa di Candle TF 5 menit dan Candle TF 1 menit.
7. Pastikan Candle TF 5 menit dan Candle TF 1 menit harus benar-benar di Atas Hull MA dan Garis tengah BB 10(Hull MA memotong ke atas garis tengah BB 10), jika Candle TF 30 dan 15 menit berwarna hijau/Up Trend
8. Pastikan Candle TF 5 menit dan Candle TF 1 menit harus benar-benar di Bawah Hull MA dan Garis tengah BB 10(Hull MA memotong ke bawah garis tengah BB 10), jika Candle TF 30 dan 15 menit berwarna Merah/Down Trend

Cara Open Posisi :
Open Posisi dengan durasi 3 menit di Candle TF 1 menit, konfirmasinya 5 tik saat candle baru terbentuk di TF 1 menit sewarna dengan candle 5 menit, misal di candle 5 menit hijau, Tunggu 5 tik saat berganti Candle baru berwarna hijau, tapi kalau merah di tik 5 Tidak Op.

Tolong di Buatkan File XML nya Mastah @Fruitfella
1. Sistem Compoud
2. Hanya sekali Open Posisi

Mohon Maaf sebelumnya.....Masih Pemula

**Comment by Yusriadi78** [comment]
Mohon di Buatkan BOT yang di atas Mastah......

@aminmarashi
@duynguyen2709
@gokula-krishna-dev
@Fruitfella
@okovalov
@biner-ex-machina

**Comment by Yusriadi78** [comment]
Tolong di bantu Mastah @AlienFly

**Comment by Yusriadi78** [comment]
Mohon bantuannya jika berkenan @Valentino242

**Comment by valentino242** [comment]
Baca strategynya jadi inget sama channelnya wibowo amin

**Comment by Yusriadi78** [comment]
@valentino242 Hahahaha
Itu memang strategi dari Om Bowo.....
