### ISSUE TITLE
Tolong Mastah Tambahkan Penjualan tersedia di BOT ini

### ISSUE THREAD

**Issue by Yusriadi78** [Fruitfella/ROBOT-binary#247]
Tolong Mastah @aminmarashi @Fruitfella  @gokula-krishna-dev  @okovalov  @AlienFly
BOT ini di tambah Penjualan tersedia Jika Rugi

[CANDLE BARU.txt](https://github.com/Fruitfella/ROBOT-binary/files/1935204/CANDLE.BARU.txt)

![tambahkan jual](https://user-images.githubusercontent.com/38336159/39091436-1b1793e6-461e-11e8-96b4-89d53003d2db.png)

**Comment by valentino242** [comment]
Coba ini : 
[Yusriadi78.zip](https://github.com/Fruitfella/ROBOT-binary/files/1935976/Yusriadi78.zip)

Ket : 
Diisi aja Cut loss berapa %nya sesuai keinginan di Block 1 ( Hasilnya bisa kurang bisa lebih karena market selalu bergerak ).

**Comment by Yusriadi78** [comment]
Ok Terimakasih @valentino242
