### ISSUE TITLE
Bagaimana Cara Open Posisi Menunggu Candle Baru

### ISSUE THREAD

**Issue by Yusriadi78** [Fruitfella/ROBOT-binary#266]
Untuk teman-teman yang berkenan membantu masalah saya.....🙏🙏🙏

Cara Open Posisi menunggu Candle Baru, perintahnya seperti apa....??

1. Saya Open Posisi pada cendle Baru terbentuk setelah berjalan 5 TIK
2. Jika Lost maupun Win maka saya tetap menunggu Candle baru terbentuk

@valentino242

**Comment by valentino242** [comment]
ini saya kasih contoh : 
Setelah new candle dan jika tick ke -5  candle = green dia OP Rise dan sebaliknya

![yusriadi78 count tick5](https://user-images.githubusercontent.com/31639222/39710818-11908978-5248-11e8-82bb-25a574f4f54d.png)
new candle ambil disini https://gist.githubusercontent.com/Fruitfella/571952f7b1e03cf0148655c8364a3214/raw/7be26e77742c8bbcd1d60bd832c808483eb5efb9/FRUITFELLA_New_Candle_v2.xml

**Comment by Yusriadi78** [comment]
@valentino242 

Apa perbedaan fungsi dari New Candle dengan Candle Is New......????

**Comment by valentino242** [comment]
Sama aja .. punya suhu fruit yg v.2  lbh cepat aja.

**Comment by Yusriadi78** [comment]
Ok makasih bro @valentino242
