### ISSUE TITLE
cara buat bot hedging 2 op bdalam 1 signal hig dan low 

### ISSUE THREAD

**Issue by indra1981** [Fruitfella/ROBOT-binary#294]

**Comment by indra1981** [comment]
ada yg bisa bantu

**Comment by valentino242** [comment]
Saat ini binary belum support untuk 2 Open secara bersamaan dalam 1 bot. Bisa diakali makai 2 BOT dan 2 browser dan dikasih counter dimasing - masing BOTnya tapi tidak saya rekomendasikan. 

Hope it help

**Comment by indra1981** [comment]
mksh om info nya pdhal klo bisa mh mntap gk bkin berat pc

**Comment by indra1981** [comment]
om mau nanya lg kalo buat step martil logika nya stake awal 1 jika terjadi los lanjut ke martil level 2 saat di level ke 2 jika tidak ada los selama 6x berturut2 maka kembali lagi ke level 1 stake nya tapi jika di level 2 ada los sebelum ke 6x op maka lanjut ke level 3 begitu seterus nya jika level 3 6 kali berturut win kembali ke level 1 lagi .... buat ngatasin minim mm bot differ jadi bisa bikin beberapa level  klo martil biasa kan klo 3x berturut2 los nyampe $100 martil ny klo dana dibwah sgitu tepok jidat dh mksh sblm nya

**Comment by valentino242** [comment]
ya ntr kalau ada waktu ya bisa dimarahi anak ini kalau kebanyakan di depan pc. Waktunya liburan soale

itu kamu beneranya mau martil atau compound atau gabungannya

* martil = menaikan jumlah lot disaat los
* compound = menaikan jumlah lot disaat profit

itu logicmu makai martingale biasa aja sudah bisa : jika profit 1 kali aja uda balik ke stake awal

pastikan pertanyaannya sejelas mungkin.  Coz paling males saya mikirin yang ga jelas. 

# IF
# DO
