### ISSUE TITLE
OUbot [Over/Under BOT]

### ISSUE THREAD

**Issue by Fruitfella** [Fruitfella/ROBOT-binary#3]
Selama kompi bermasalah, tiba2 dapet ide.
Digit betting Over/Under memiliki return yg dinamis, bergantung pada angka betting yg kita pilih.
kira2 returnnya 10%-800%, wow? belum tentu.
teknikal analisis tidak dapat digunakan pada Digit betting, karna pada dasarnya betting berarti tebak2an, jika benar anda beruntung, jika salah anda buntung.
tapi tebak2an bukan berarti nasib2an, tebak2an bisa diperbesar ketepatannya dengan teori kans, teori peluang.

contoh:
pada Digit betting Over/Under dengan return 10%-15%an (saya males ngitungnya hehe) peluang untuk betting anda tepat adalah 1:9, ini bukan berarti setiap 10x bet anda bisa menang 1x dan kalah 9x. ini juga bisa berarti anda menang 9x - kalah 1x, atau mungkin malah kalah 10x.
kok bisa? bukannya 1:9?
1:9 juga berarti dalam 100x bet anda akan menang 10x - kalah 90x. jadi mungkin anda harus kalah dulu 90x baru bisa menang 10x. disini kalau anda cuma bet 10x, maka anda sudah pasti kalah.

btw tu de poin.
OUbot memilih bet dengan return tidak jauh diatas 100%, pilihan ini diambil agar setelah loss kerugian kita bisa cepat kembali, sementara peluang win nya tidak terlalu kecil.
Oubot hanya perlu menentukan 2 pilihan (besar/kecil), ini membuat peluang untuk win menjadi fifty fifty. hampir sama dengan Even/Odd (dua pilihan), hanya bedanya even/odd murni tebak2an dan sulit diprediksi, namun besar/kecil bisa diperkirakan dengan teori kecenderungan.
OUbot akan menentukan apakah akan bet over atau bet under bergantung pada situasi, yaitu manakah lebih banyak angka yang muncul pada kurun waktu tertentu, angka besar atau kecil.

oke, waktu merakit OUbot

**Comment by Fruitfella** [comment]
OUbot telah selesai dirakit. tinggal tes uji coba, moga berhasil dan gak da error.

**Comment by Fruitfella** [comment]
Oke sekarang waktunya tes Oubot ver 0.1.7

![ou1](https://cloud.githubusercontent.com/assets/26277327/25962768/40b9a3c6-36a9-11e7-9811-8d9aac489b65.PNG)

--------------------------------------------------------
![ou2](https://cloud.githubusercontent.com/assets/26277327/25962789/50686334-36a9-11e7-915d-4c4c1751b909.PNG)

Keterangan : 
**Balance** - Jumlah kapital pada akun, $3489.88 pd saat uji coba dimulai
**KeepMoney** - Jumlah uang yg di simpan (tdk dipakai untuk trading dalam kondisi apapun) $2989.00 , ini berarti jumlah uang yg dipakai untuk trading hanya $500, jika $500 tsb habis terpakai maka bot akan otomatis berhenti.
**Alternate** - Strategy alternatif yg digunakan pada saat loss beruntun.
**TargetProfit** - Jumlah profit yg ditargetkan. $2000, bot akan berhenti setelah berhasil mencapai profit $2000
**ConsecutiveLoss** - Jumlah maksimal loss beruntun yg terjadi. 100, berarti bot akan berhenti setelah 100 kalah secara beruntun (ini tidak mgkn terjadi karna balance keburu habis, lol)
**InitialAmount** - Minimal jumlah uang yg dipakai per transaksi.
**MartiLossLevel** - Maksimal step pada menejemen martingale ketika loss.
**MartiWinLevel** - Maksimal step pada menejemen martingale ketika win.
**MartiFactor** - Faktor multiplikasi pada manajemen martingale.

oke, tinggal tunggu hasilnya besok pagi, sekarang waktunya molor...

**Comment by Fruitfella** [comment]
kebangun di jam 3:20. oubot berhenti dgn stoploss dan rugi.
![ou3](https://cloud.githubusercontent.com/assets/26277327/25970701/c2a9b60e-36c3-11e7-9a91-82d3c5b2b2d4.PNG)

saldo tinggal $2990.46 tdk melewati $2989.00. artinya sistem keepmoney berjalan baik, cuma strategynya tdk berjalan baik dan rugi. perlu perbaikan untuk oubot berikutnya

**Comment by Fruitfella** [comment]
setelah selesai di edit, sekitar jam 4:00. OUbot ver 0.1.1 langsung dites. hasilnya oke.
![ou4](https://cloud.githubusercontent.com/assets/26277327/25980679/6c6bd90c-36fa-11e7-90bd-d903504e7826.PNG)

perbahannya pada digit yg dipilih, yaitu yg peluang win nya lebih besar tapi returnnya tidak terlalu jauh dari stake (96%, ini sama dengan return utk rise/fall).
kapital yg digunakan masih sama $500, begitu jg setingan yg lain, TP $1000.
sampai jam 09:56 terjadi 1553 trades dengan 786 wins dan 766 losses (% win lebih besar).
profit $664.15 (lebih dari 100% kapital) dengan Loss Level 7 (artinya loss beruntun terpanjang adalah 7 step, $127)
masih belum menyentuh TP ($1000) tapi bot akan saya stop coz perlu rehat, XD.
bot ini boleh dibilang oke, tapi 1x tes belum bisa menentukan performa bot yg sebenarnya, mgkn pada keadaan market berbeda hasilnya bisa saja sangat jelek.
btw, its worth a celebrate!

**Comment by Fruitfella** [comment]
tes berikutnya untuk OUbot, moga aja quota internetnya cukup, lg bokek XD.
![ou5](https://cloud.githubusercontent.com/assets/26277327/25996909/d0ae5aea-3743-11e7-92e5-e1b2b92902ea.PNG)
![ou6](https://cloud.githubusercontent.com/assets/26277327/25996916/dc6fe0e2-3743-11e7-95bd-42771a989c35.PNG)

**Comment by Fruitfella** [comment]
hampir 1 jam kemudian waktu saya cek, losing level sudah sampai ke step 7($127).
![ou7](https://cloud.githubusercontent.com/assets/26277327/25998206/0ecf3f32-374a-11e7-8100-dea0983445f5.PNG)

ini loss beruntun step 6 ($63) sebelum akhirnya profit dan losses terbayar.
![ou8](https://cloud.githubusercontent.com/assets/26277327/25998214/1859e4da-374a-11e7-8b3e-2ab753d70950.PNG)

**Comment by Fruitfella** [comment]
sudah dapet peringatan dari telekkomsel *sigh*. OUbot saya stop untuk menghindari kuota inet habis saat bot dalam keadaan loss di step +5 yg kerugiannya cukup besar.
![ou9](https://cloud.githubusercontent.com/assets/26277327/25998447/2695e200-374b-11e7-89af-1eb49ba3a644.PNG)

**Comment by Fruitfella** [comment]
Oubot di tes kembali 13 mey 2017 jam 04:40
KeepMoney $3293.39 yg artinya kapital yg di pakai utk trade hanya $500.
settingan yg lain masih tetap sama dengan sebelumnya
![ou10](https://cloud.githubusercontent.com/assets/26277327/26018125/46c9eab6-3797-11e7-89d7-f2a23de13017.PNG)
![ou12](https://cloud.githubusercontent.com/assets/26277327/26018132/4f93d1b6-3797-11e7-87f9-f1f5eca2fda9.PNG)

**Comment by Fruitfella** [comment]
satu jam kemudian
![ou13](https://cloud.githubusercontent.com/assets/26277327/26019585/98f5e4f8-37a0-11e7-989f-96b10fd853db.PNG)

**Comment by Fruitfella** [comment]
satu jam kemudian
![ou12](https://cloud.githubusercontent.com/assets/26277327/26019602/c1d6ed18-37a0-11e7-911d-94f8de5428f2.PNG)

**Comment by Fruitfella** [comment]
![ou3](https://cloud.githubusercontent.com/assets/26277327/26020396/0e7f7930-37a8-11e7-91ce-c7d563e71b68.PNG)

setelah dua jam berjalan, oubot berhasil melakukan 553 trades dengan total profit $226.8
profit ini bisa dibilang cukup besar, hanya sayangnya losing level mencapai 8 step ($255). mgkn ini alasan kenapa profit di 1jam kedua ini lebih kecil dibanding satu jam sebelumnya.
losing level 8 step ini juga sangat berbahaya seandainya terjadi diawal ketika bot dijalankan. loss $255 ini lebih dari setengah kapital yg dipakai ($500) yg artinya loss ini tdk dpt di tanggulangi dengan martingale. tentu saja dengan sistem oubot yg mumpuni, oubot akan tetap berjalan dan menanggulangi loss tersebut 2 jam kemudian (berdasarkan data bahwa oubot dpt memperoleh profit lebih dari $200 dalam 2 jam) dan akhirnya dalam jangka panjang (+5jam) oubot akan dpt memperoleh profit. dengan catatan : jika loss 8x beruntun ini tdk terjadi berulang2.

**Comment by Fruitfella** [comment]
![ou3](https://cloud.githubusercontent.com/assets/26277327/26020521/98f68dfa-37a9-11e7-9bec-8b6fcc490bcf.PNG)

setelah dua jam berjalan, oubot berhasil melakukan 553 trades dengan total profit $226.8
 profit ini bisa dibilang cukup besar, hanya sayangnya losing level mencapai 8 step ($255). mgkn ini alasan kenapa profit di 1jam kedua ini lebih kecil dibanding satu jam sebelumnya.
 losing level 8 step ini juga sangat berbahaya seandainya terjadi diawal ketika bot dijalankan. loss $255 ini lebih dari setengah kapital yg dipakai ($500) yg artinya loss ini tdk dpt di tanggulangi dengan martingale. tentu saja dengan sistem oubot yg canggih, oubot akan tetap berjalan dan menanggulangi loss tersebut 2 jam kemudian (berdasarkan data bahwa oubot dpt memperoleh profit lebih dari $200 dalam 2 jam) dan akhirnya dalam jangka panjang (+5jam) oubot akan dpt memperoleh profit. dengan catatan : jika loss 8x beruntun ini tdk terjadi berulang2.

**Comment by Fruitfella** [comment]
ohhh i need to get some sleep.
![ou4](https://cloud.githubusercontent.com/assets/26277327/26021562/9f675528-37ba-11e7-86e2-09a7d136188e.PNG)

itll take at least 6h more to touch the target profit. ill leave it by its own, hope nothing bad would happen during my sleep.

**Comment by Fruitfella** [comment]
kebangun jam 2 kurang, ternyata bot sudah take profit $1000, gak tau kpn pastinya bot menyentuh batas TP, tapi ini cukup menunjukan bahwa oubot berhasil take profit 2x kapital yg dipakai untuk trading dalam kurang dari 10 jam dan jumlah total transaksi sebanyak 2288x.

![ou5](https://cloud.githubusercontent.com/assets/26277327/26023396/b89b0f7e-37e4-11e7-9ac5-7bcaf0f26462.PNG)
![ou6](https://cloud.githubusercontent.com/assets/26277327/26023398/c13a8dbc-37e4-11e7-8328-6e757714bed1.PNG)

informasi yg muncul saat oubot berhenti terdapat kesalahan, yaitu **winning level** 0 sebenarnya pasti lebih dari itu, dan **losing level** 7, padahal dalam 2 jam oubot berjalan lossing level sudah mencapai step 8. akan tetapi kesalahan ini tidak berpengaruh apa2 pada kinerja oubot saat melakukan trading, karena ini hanyalah kesalahan print info yg tidak ada hubungannya dengan perhitungan yg dilakukan sebelum open purchase.

2 kesalahan ini akan menjadi target perbaikan berikutnya untuk upgrade oubot ke versi 0.1.2 yg rencananya akan di ujicoba lusa jam 8 pagi.

anyway this is worth celebrating!! :+1:

**Comment by Fruitfella** [comment]
setelah dipikir2, saya merasa ada beberapa parameter oubot yg sebenarnya tidak diperlukan.
![oudit](https://cloud.githubusercontent.com/assets/26277327/26023659/749b819e-37eb-11e7-8aca-1d2c82e6f6bd.png)

**ConsecutiveLoss** -> dengan adanya parameter KeepMoney, parameter yg berfungsi sebagai stop loss ini kehilangan gunanya.
**MartiLossLevel** -> parameter yg berfungsi untuk mengatur tingkat martingale ini tidak berguna untuk oubot karena sistem pada oubot yg dirancang untuk mengatur tingkat martingale secara otomatis jika balance tidak cukup untuk meneruskan martingale step.
**MartiWinLevel** -> ini parameter yg berfungsi untuk meningkatkan profit pada bobot ver 0.1.8, tapi pada oubot, parameter ini bisa jadi bom bunuh diri karena perbedaan strategy antara oubot dan bobot yg significant.

parameter ini rencananya akan saya hilangkan pada upgrade oubot berikutnya.

**Comment by Fruitfella** [comment]
waktunya tes **OUbot ver. 0.2.1**
beberapa parameter yg tidak perlu sudah dibuang, **KeepMoney** (uang yg ingin dipakai utk trade) diganti dengan **TradeMoney** (jumlah uang yg dipakai utk trade).
![oubot_shot](https://cloud.githubusercontent.com/assets/26277327/26039498/b8f4abf8-3945-11e7-8fad-4146c3ecd07a.PNG)
![ou7](https://cloud.githubusercontent.com/assets/26277327/26039502/c0422c96-3945-11e7-91f8-7c5a1f212a08.PNG)

diperkirakan oubot akan take profit dalam waktu 10 jam, yaitu sekitar jam 18:00  wib.

**Comment by Fruitfella** [comment]
waktunya tes **OUbot ver. 0.2.1** ✌️ 
beberapa parameter yg tidak perlu sudah dibuang, **KeepMoney** (uang yg tdk ingin dipakai utk trade) diganti dengan **TradeMoney** (jumlah uang yg dipakai utk trade).
![oubot_shot](https://cloud.githubusercontent.com/assets/26277327/26039550/4381b59a-3946-11e7-8d32-c0cd297a9012.PNG)
![oubot_shot](https://cloud.githubusercontent.com/assets/26277327/26039555/4a5246d2-3946-11e7-9cbb-9209bf1f2351.PNG)

diperkirakan oubot akan take profit dalam 10 jam, yaitu sekitar jam 18:00 wib.

**Comment by Fruitfella** [comment]
waktunya tes OUbot ver. 0.2.1 ✌️
beberapa parameter yg tidak perlu sudah dibuang, KeepMoney (uang yg tdk ingin dipakai utk trade) diganti dengan TradeMoney (jumlah uang yg dipakai utk trade).
![oubot_shot](https://cloud.githubusercontent.com/assets/26277327/26039570/79bf8498-3946-11e7-804d-b57c379e788d.PNG)
![ou7](https://cloud.githubusercontent.com/assets/26277327/26039572/87542154-3946-11e7-80ad-2490f3ea8e9c.PNG)

diperkirakan oubot akan take profit dalam 10 jam, yaitu sekitar jam 18:00 wib.

**Comment by Fruitfella** [comment]
bangun jam setengah 2, saya cek oubot, ternyata mati, bukan TP ataupun SL. apa sebabnya mati sendiri masih blm diketahui.

**Comment by Fruitfella** [comment]
![ou8](https://cloud.githubusercontent.com/assets/26277327/26045804/0ad4e016-3976-11e7-9915-0ff7f783a8f5.PNG)

**Comment by Fruitfella** [comment]
beberapa menit kemudian terjadi kerugian. setelah loss beruntun 8x tapi oubot tdk mati melainkan menejemen martingale reset ke initial stake. ini artinya tidak ada yg salah dengan sistem menejemen martingale. jd alasan kenapa oubot td mati sebelum TP/SL masih tanda tanya. mgkn kompi yg rusak atau jaringan internet yg bermasalah? karna memang terkadang jaringan broadband ini sering bermasalah.
i
![ou9](https://cloud.githubusercontent.com/assets/26277327/26046054/47e2eee8-3977-11e7-9e83-1637cd697a00.PNG)

**Comment by Fruitfella** [comment]
satu masalah berhasil ditemukan. ada kesalahan pada logika oubot ketika merubah jenis purchase over/under sehingga oubot tidak lagi trade berdasarkan strateginya. sudah di fix, semoga tidak ada kesalahan yg lain yg timbul sewaktu upgrade sebelumnya..

**Comment by Fruitfella** [comment]
OUbot ver. 0.2.2e sudah fixed. parameter TrailingStop ditambahkan.
waktunya tes.
![ou-shot](https://cloud.githubusercontent.com/assets/26277327/26085182/7e41953a-3a0c-11e7-859e-0df63aca4b31.PNG)
![ou10](https://cloud.githubusercontent.com/assets/26277327/26085187/84083dac-3a0c-11e7-95d4-4c919c9ee50a.PNG)

**Comment by Fruitfella** [comment]
Karena setelah ujicoba sewaktu memperbaiki oubot, balance sudah mencapai 5k lebih (10x trade money yg digunakan sebelumnya) maka **TradeMoney** dinaikan menjadi $5000, **TakeProfit** $5000, **InitialAmount** $10. Parameter baru **TrailingStop** $200.
berdasarkan performa sebelumnya, diperkirakan oubot akan take profit dalam 2-3 jam.

**Comment by Fruitfella** [comment]
1 jam kemudian oubot mengalama kerugian, tapi oubot masih berjalan dan berusaha mengembalikan duit yg loss.
![ou11](https://cloud.githubusercontent.com/assets/26277327/26086432/bfb2827e-3a14-11e7-8f05-ef636d5883c3.PNG)

**Comment by Fruitfella** [comment]
1 jam kemudian oubot mengalami kerugian karena loss beruntun 9x. tapi oubot masih terus berjalan dan berusaha mengembalikan duit yg loss yg kira2 akan dicapai dalam waktu 30-60 menit
![ou11](https://cloud.githubusercontent.com/assets/26277327/26086503/3b22318e-3a15-11e7-8a73-2c57c933a8ce.PNG)

**Comment by Fruitfella** [comment]
1 jam kemudian oubot mengalami kerugian karena loss beruntun 9x. tapi oubot masih terus berjalan dan berusaha mengembalikan duit yg loss yg kira2 akan dicapai dalam waktu 30-60 menit.
![ou11](https://cloud.githubusercontent.com/assets/26277327/26086568/abdca2f6-3a15-11e7-8118-b3baf4a053f0.PNG)
jika di perhatikan dari **Saving** yg sebelumnya $859.29 menjadi $1867.85, ini berarti sebelum loss beruntun mencapai level 9, oubot sudah profit sebesar $1008.56 (1867.85-859.29).

**Comment by Fruitfella** [comment]
karena ada urasan mendadak. kemarin sampe lupa snapshot hasil tes nya. Tapi gak masalah karena Oubot test akan saya tutup. alasannya? udah yg beli, hahaha.
OUbot sudah dibeli dengan persyaratan bahwa OUbot secara eksklusif hanya boleh dipakai oleh saya dan pembeli. :1st_place_medal:

**Comment by hsunarso** [comment]
![gbr 1](https://user-images.githubusercontent.com/38837776/43937318-209e2360-9c87-11e8-8991-c56983635280.PNG)
)
ada yang bisa bantu ndak ya, bagaimana caranya menjumlahkan digit 1 dengan digit 2 dari belakang
contoh : 
price 600.4612
digit 1 = 2
digit 2 = 1
digit 3 = 6
digit 4 = 4

var a = digit 1 + digit 2 = 2 + 1 =3
var b = digit 3 + digit 4 = 6 + 4 = 10

**Comment by Abicombeyy** [comment]
Kurang tau bos....smpyan maen pakai jumlah digit atau gimna...??

Pada tanggal Jum, 10 Agt 2018 10.27, hsunarso <notifications@github.com>
menulis:

**Comment by ricothenfx** [comment]
Masih butuh gak gan ?

**Comment by Abicombeyy** [comment]
Ada yang baru kah.....??

Pada tanggal Kam, 22 Agt 2019 15.30, ricothenfx <notifications@github.com>
menulis:

**Comment by Abicombeyy** [comment]
Brooooooo....

Pada tanggal Min, 25 Agt 2019 14.56, combey bi'in <combeyy@gmail.com>
menulis:
