### ISSUE TITLE
TOUCH martingale in opposite 

### ISSUE THREAD

**Issue by zdradozhi** [Fruitfella/ROBOT-binary#300]
Hello dear friends, can anyone help to change a bot to trade not rise/fall in opposite direction after loss  but TOUCH with martingale method and in opposite direction (+/-) after every loss?
Thanks in advance for any help!

Here is the original rise/fall bot without martingale
[Call_Put-Strategy.zip](https://github.com/Fruitfella/ROBOT-binary/files/2126477/Call_Put-Strategy.zip)

**Comment by valentino242** [comment]
I can help You . Contact My email 
valentino.cakrawala@gmail.com
