### ISSUE TITLE
Cara Copy Paste bot Binary versi XML

### ISSUE THREAD

**Issue by elhazain** [Fruitfella/ROBOT-binary#305]
Mohon bantu cara gabungin bot satu dengan lainnya dengan cara Copy Paste....apakah bisa ...?

**Comment by baruga** [comment]
@elhazain bisalah browwwwww

**Comment by elhazain** [comment]
Wehehehehehe ajari doong

**Comment by baruga** [comment]
@elhazain itu lho brow yang ada tulisannya membaca setiap tick yang baloknya warna kuning.. Bloknya sampeyan seret kesitu lantas di donlot. lalu buka file pertama yang akan di gabungkan dengan yang kedua.. 
setelah file pertama kebuka... buka itu donlotan tadi...

Tralalaaaaa filenya ada terkumpul disitu... gitu lho bro lantas simpan filenya supaya 2 bot tadi jadi 1..

**Comment by dabsulistyono** [comment]
@baruga  ada kontak yg bisa dihubungi...
mksh...

**Comment by baruga** [comment]
@dabsulistyono ppaybiz@gmail.com bisa juga disini di forum ini

**Comment by elhazain** [comment]
wah sip sudah bisa veroh ..makasih veroh @baruga
