### ISSUE TITLE
candle berurutan

### ISSUE THREAD

**Issue by karing-sidikalang** [Fruitfella/ROBOT-binary#31]
@Fruitfella 
![111](https://user-images.githubusercontent.com/28832596/27537993-a9c86744-5aa8-11e7-8a95-6060ed7a4133.jpg)

bro ku, minta tolong lah,

gimana untuk OP pada candle berikutnya kalau mengikuti pola candle di atas. trims

**Comment by Fruitfella** [comment]
kurang jelas itu strategynya @karing-sidikalang .
itu OPnya dimana? di lingkaran hijau dua2nya atau cuma lingkaran hijau kedua?
trus trendnya ikut dihitung atau gak?

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
