### ISSUE TITLE
tolong mas

### ISSUE THREAD

**Issue by apaajadehbos** [Fruitfella/ROBOT-binary#32]
saya minta tolong mas, gini, gimana bikin di blok T2 itu. 
candle 1 menit berakhir pada detik ke 60, kemudian OP langsung di candle baru berikutnya setelah 6 detik datang candle baru..mohon bantuannya. trims

**Comment by ubanemas** [comment]
beliau lagi sibuk mas, mungkin saya coba bantu jawab, klo salah mohon dikoreksi :)
![2017-07-05 21_28_24-binary bot](https://user-images.githubusercontent.com/27851415/27869091-0c71cf76-61c9-11e7-80b7-5ffa15c2a240.jpg)
apakah yang dimaksud seperti ini, jika new candle, tunggu 6 detik kemudian purchase...

**Comment by ubanemas** [comment]
![2017-07-05 21_40_46-greenshot](https://user-images.githubusercontent.com/27851415/27869630-b5cde3ec-61ca-11e7-9012-2c1a1bf803a2.jpg)
![2017-07-05 21_37_10-greenshot](https://user-images.githubusercontent.com/27851415/27869643-c0afe760-61ca-11e7-9ca9-830954d5a603.jpg)

**Comment by apaajadehbos** [comment]
halo mas, kalau bisa bukan pada candle baru, tapi pada akhir candle mas..jadi candle berakhir, baru purchase setelah menunggu 6dtk

**Comment by Fruitfella** [comment]
Gak mudeng aq sama pertanyaanya, candle berakhir bukannya hampir
bareng sama candle baru? candle close & candle open cuma beda 1 tick.
kalo mau eksekusi yg lebih akurat silahkan upload strategynya, atau
jelasin teorinya jg boleh, biar aq tau perhitungan waktu eksekusinya
yg tepat.
