### ISSUE TITLE
mohon bantuannya donks buat bikin bot R/F

### ISSUE THREAD

**Issue by AAGINZ** [Fruitfella/ROBOT-binary#340]
![zz](https://user-images.githubusercontent.com/43108189/46296000-8fffca00-c5c3-11e8-9823-f36c6daa104f.jpg)

kalau misalnya dalam setiap tick ketemu angka sama seperti di atas gambar kita bisa pilih raise atau fall sesuai yang kita inginkan cuman patokannya tick 1 dan tik 2 dengan 3 angka yg sama

**Comment by lighterland** [comment]
![image](https://user-images.githubusercontent.com/43042301/46325992-7d0cea00-c603-11e8-9640-daeea4f3f9de.png)

**Comment by AAGINZ** [comment]
maap itu gimana cara kerjanya 
udah di coba ga mau berfungsi 

> 
> 
> ![image](https://user-images.githubusercontent.com/43042301/46325992-7d0cea00-c603-11e8-9640-daeea4f3f9de.png)

**Comment by AAGINZ** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/43042301/46325992-7d0cea00-c603-11e8-9640-daeea4f3f9de.png)

itu gimana cara kerjanya udah di coba ga mau berfungsi
