### ISSUE TITLE
Modes Median DD Bot

### ISSUE THREAD

**Issue by Skatezboy** [Fruitfella/ROBOT-binary#40]
Mas, mau tanya ni , apakah bisa kita buat bot digit dengan modes/median dari record 8 tick sebelumnya?
misal, record last digit seperti ini
tick 1 >> 9
tick 2 >> 9
tick 3 >> 5
tick 4 >> 3
tick 5 >> 2
tick 6 >> 1
tick 7 >> 2
tick 8 >> 3
tick 9 >> 0

nah, dari record diatas apakah bisa dipakai dengan fungsi med mod yang ada dalam tab Math?
makasih sebelumnya

**Comment by Fruitfella** [comment]
@Skatezboy 
median = HxL/2 , ini utk candle.
klo yg kamu maksud itu nilai rata2nya (semua dijumlahin trus dibagi 9) pake `average`

**Comment by Skatezboy** [comment]
![analisator](https://user-images.githubusercontent.com/7279426/28482770-1bb98136-6e94-11e7-8908-2eaa1c9c7893.JPG)


saya buat seperti ini , tolong dikoreksi mas 

analisanya pakai average yang kata mas tadi, jika hasil nya 0-9 purchase differs, jika hasil >9 maka kmbali analisa lagi

**Comment by Fruitfella** [comment]
itu hasilnya gak mungkin bisa 0-9, jd itu pasti puchase differ terus, karna pake `Ticks List` 
Kalo pake `Last Digit` hasilnya malah gak mungkin > 9

**Comment by Skatezboy** [comment]
jadi intinya gak mungkin bisa ya mas?
coba mas pake file ini mas untuk predictor DD cuma saya tidak tau rumusnya
https://drive.google.com/open?id=0B4Ujsny5sdHrWFNGa19oTnRBLTA

**Comment by Fruitfella** [comment]
Perlu diingat kalo `Last Digit` berkisar antara 0-9, jadi nilai rata2nya jg antara 0-9. nilai 0 hanya terjadi kalo semua datanya bernilai 0, begitu jg dgn 9.
Linknya nanti aja aq check.
Ini aq kasih contoh membuat list dan menghitung rata2 10 ticks.
![picture01](https://user-images.githubusercontent.com/26277327/28484458-a7dbc626-6e9c-11e7-917c-6fb469498885.png)

**Comment by Skatezboy** [comment]
saya coba dulu mas  makasih sebelumnya, nanti saya upload hasilnya

**Comment by Fruitfella** [comment]
Ooopsie, ada yg salah tuh penjelasan gambarnya.
*kalo 0-4 dia purchase, tapi kalo > 4 dia analisa lg. 
note: 4,0001 juga >4 sampe infinit, tapi karna data rata2 tertinggi cuma 9 jd ya cuma sampe 9.

**Comment by Fruitfella** [comment]
Oops, sering salah klik waktu komen _lol_
jd ketutup.

**Comment by Skatezboy** [comment]
kalau purchasenya dibuat supaya hasil dari average gimana mas? kalau misal hasilnya >9 dia akan analisa lagi sampai dia nemu averagenya <10
hehhe maaf ngerepoti soalnya forum disebelah gak tau bahasanya

**Comment by Fruitfella** [comment]
average adalah nilai rata2 jadi mustahil >9
sebenernya strategynya gimana sih? bisa dijelasin rinci? mgkn bukan pake average itu, karna average (nilai rata2) gak akan melebih nilai tertinggi yg ada. misal disekolah nilai tertinggi 10, gak akan ada yg dapet nilai rata2 lebih dari 10. malah nyatanya gak ada yg dapet nilai rata2 10, paling tinggi cuman 9 koma sekian.

**Comment by Skatezboy** [comment]
strateginya gini mas
LDP di dapatkan dari analisa 10 tick 
post pertama kan saya tanya bagaimana caranya menggunakan median dan modus, karena setau saya pada matematika  modus digunakan sebagai pencari angka yang paling sering keluar
misal
tick.1 >> Last digit 9
tick.1 >> Last digit 9
tick.2 >> Last digit 1
tick.3 >> Last digit 2
tick.4 >> Last digit 4
tick.5 >> Last digit 8
tick.6 >> Last digit 9

dalam 6 tick kita mendapat data
angka 9 >> ada 3
angka 1 >> ada 1
angka 2 >> ada 1
angka 4 >> ada 1
angka 8 >> ada 1

maka modusnya adalah 9
nah kita ambil LDP 9, gitu mas
maaf kalau ribet jelasinnya

**Comment by Fruitfella** [comment]
oh, kalo gitu yg dipake ya `Modes' , cuma hasil `Modes` bisa lebih dari 1, nah klo gitu trus gimana?

**Comment by Skatezboy** [comment]
kalau modes nya lebih dari 1 skip 1 op mas

**Comment by Fruitfella** [comment]
Bisa, tapi op pertama harus dikorbankan, maksudnya op pertama gak bisa sesuai perhitungan karna sistem binary bot mewajibkan Trades option harus diisi sebelum bot jalan.

**Comment by Skatezboy** [comment]
iya gpp mas itu resiko mknya nt rencana saya buat marti

**Comment by Fruitfella** [comment]
btw, `Modes` jg gak mgkn bisa >9 😛

**Comment by Skatezboy** [comment]
kalau di bot binary bagaimana system modesnya mas?

**Comment by Fruitfella** [comment]
maksudnya nilainya gak mungkin >9 kan datanya cuma 0-9

**Comment by Skatezboy** [comment]
iya khan diambil dari data terbanyak keluar mas, memang digit khan dari 0-9 . gitu mas. kira-kira bisa gak?

**Comment by Fruitfella** [comment]
ada lg satu masalah penting. waktu OP Match/Differ digit yg diambil dalam kontrak adlh digit 1 tick setelah kita purchase. misal skr kita purchase di last digit 8, kontrak yg diambil adalah 1 tick kemudian, misal 3. jd yg dihitung differ 3. Ini memang udah aturan dari sono termasuk trading manual jg gitu.
ini botnya.

**Comment by Skatezboy** [comment]
iya memang mas setidaknya kita bisa analisa setelah angka yang sering keluar kemungkinan kecil untuk keluar secara beruntun

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/28486495-70a97c6a-6eac-11e7-8b46-ce6e482fde8b.PNG)

**Comment by Skatezboy** [comment]
terima kasih mas , saya akan running  selama 24 jam untuk tes berapa marti terdalamnya. saya akan report kesini lagi. kalau mas mau running tes bot berjam-jam monggo mas kabari saya komputer server saya OL 24 jam

**Comment by Fruitfella** [comment]
Sip! nanti klo aq ada bot yg perlu test, pasti minta tolong situ 😄

**Comment by Skatezboy** [comment]
oiya mas, kalau misal waktu purchase, analisa ticknya berhenti gimana? jadi analisa ticknya menunggu setelah purchase selesai..

**Comment by Fruitfella** [comment]
Tarok semua yg di block orange ke main block P(2), tarok dipaling atas, jgn dibawah `If`

**Comment by Fruitfella** [comment]
tunggu, maksudnya gimana? analisanya restart? ngulangin lg ngisi listnya satu-persatu dari awal?

**Comment by Skatezboy** [comment]
analisa restart dari 0 lagi mas

**Comment by Skatezboy** [comment]
nunggu ngisi list satu persatu

**Comment by Fruitfella** [comment]
kalo itu cuma perlu Duplicate/Copy block `Set [lastDigitList] to` `Create empty list` keatas `Purchase Differs`

**Comment by Fruitfella** [comment]
Oops salah, copy keatas `Trade again` di main block F(4)

**Comment by Skatezboy** [comment]
![analisa](https://user-images.githubusercontent.com/7279426/28486861-4c99e738-6eb1-11e7-973e-225371bdf1fa.png)
hasil dari modesnya kok gak sesuai dengan purchase ya mas?

**Comment by Fruitfella** [comment]
Kan udah dibilang, kalo angka yg diambil 1 tick setelah purchase. Buka chart nya, liat waktu purchase ada garis Start->Entry spot->Expiry
Start itu waktu kita purchase, Entry = price/digit yg dipakai pd kontrak, Expiry waktu kontrak close.
dari Start ke Entry itu 1 tick, kalo Entry ke Expiry itu sesuai Durasi yg kita pilih.

**Comment by Skatezboy** [comment]
misalnya ini mas , hasil dari analisa modes nya 7 seeperti di atas, LDP nya set di 7 , bisa gak mas

**Comment by Fruitfella** [comment]
Ya gak bisa, itu udah aturan binary trading, disemua broker jg begitu.
coba aja trading manual di binary.com atau broker laen, trus OP differ pas di digit 8 misal, pasti itungannya dimulai dari digit yg setelah itu, bukan digit 8.

**Comment by Fruitfella** [comment]
Sorry, kayaknya aq salah teori... Digit betting beda dgn opsi yg laen _lol_
Jadi kemungkinan (secara teori) bisa itu bikin predictionnya sama dgn hasil analisa, cuman aq belom tau caranya, nantilah aq riset dlu..

**Comment by Skatezboy** [comment]
nah itu dia mas , minta tolong banget mas

**Comment by Skatezboy** [comment]
saya bingung mas , sudah coba banyak cara , saya kasi var LDP, kemudian change LDP by (modes of tick) malah keluarnya barrier is not integer from 0 to 9

**Comment by Fruitfella** [comment]
udah bisa @Skatezboy , cuma ada beberapa sinyal yg mgkn dilewatkan, tapi OP udah sesuai dgn prediksi.

**Comment by Fruitfella** [comment]
Klik kanan <a href="https://gist.githubusercontent.com/Fruitfella/974fec1a7ee756d93ac22d07188a77f5/raw/c5cc90445d0420c25444679b478dbe45229e3428/Modes_Digit_Differ.xml">link ini</a> trus `Save link content as..` trus `Save`

**Comment by Skatezboy** [comment]
saru lagi mas, add martina yang gak bisa, aku udah coba FM yang  sampean share tapi martingale nya gak jalan. 
misal 
stake : 0.35
marti level 1 if loss : 3.6
marti level 2 if loss : 37
minta tolong mas

**Comment by Fruitfella** [comment]
untuk FM coba ganti marti factor nya sekitar 9.3

**Comment by Fruitfella** [comment]
Tools yg aq share, asal di download sesuai petunjuk dan dipasang sesuai gambar pasti jalan (mungkin 😛) _lol_ ! untuk FM sebaiknya pake yg versi 2.1, versi 3.0 itu permintaan org mgkn gak cocok utk kebanyakan strategy.

**Comment by prediction01** [comment]
Tôi có một bot thống kê trong 6 tick nếu số 0 về nhiều thì sẽ vào lệnh " khác 0 sau 5 giây" cần thì liên hệ tôi nhé. Hoangvan3748@ gmail.com

**Comment by zairisatria** [comment]
saya sudah lakukan analisa manual dan dapat strategi yang minim sekali tingkat lossnya:
- analisa berlaku hanya per candle
- jika candle baru maka dapatkan angka 5 pertama dan dapatkan angka 5 kedua dan OP differ ketika tick candle naik (naik secara signifikan) dalam dua tick.

penjelasan: karena ketika ada trend dari tik sebelumnya naik dalam dua tik da sebelumy ada angka lima range nilai kenaikannya jarang sekali/tidak pernah menyentuh angka 5 di digit terakhir

mohon yang bisa bikin bot nya para master.. salam dari zairi anak baru dri kalimantan

**Comment by Rifqi0999** [comment]
> udah bisa @Skatezboy , cuma ada beberapa sinyal yg mgkn dilewatkan, tapi OP udah sesuai dgn prediksi.

Boleh bagi mas?plis
