### ISSUE TITLE
minta reques revisi bot digit differ

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#45]
Req digit differ dengan ldp mengikuti angka spot mulai dari ldp 0 op saat angka spot 0 , ldp 1 op mengikuti angka spot 1 begitu seterus nya sampai ldp 9 dia akan op di angka spot 9  
![received_500914086916396](https://user-images.githubusercontent.com/28952744/28747623-fed8d860-74cd-11e7-9323-67d4f8a98573.png)

**Comment by Fruitfella** [comment]
coba tes ini
![capture](https://user-images.githubusercontent.com/26277327/28747844-b75a4a28-74d2-11e7-91a0-b9e5725e6a29.PNG)

**Comment by sinung21** [comment]
OK terimakasih @Fruitfella anda memang master bot. terimaksih sekali lagi

**Comment by Fruitfella** [comment]
Aq baru aja cek, ternyata sistem dasar binary bot " **Trade Options** diproses lebih dulu sebelum analisa diproses" ini beda dgn perkiraan q "setiap variable baru dipanggil/dijalankan ketika dibutuhkan".
jadi untuk strategy kamu, contoh diatas bisa meleset. Jadi coba di tes dulu bandingkan dgn yg ini. jgn lupa nanti kasih tau aq hasilnya mana yg lebih akurat.
![capture](https://user-images.githubusercontent.com/26277327/28749124-c7ff5b10-74e7-11e7-87ad-04befbf59e51.PNG)

**Comment by sinung21** [comment]
gambar apa itu mas?

**Comment by Fruitfella** [comment]
Corrupted/rusak kayaknya itu gambar. lol
gak tau kenapa.
coba liat di emailmu, rusak gak yg dikirim github ke emailmu?

**Comment by sinung21** [comment]
jadi LDP di ganti prediksi yah mas

Pada 30 Juli 2017 05.28, Fruitfella <notifications@github.com> menulis:

**Comment by Fruitfella** [comment]
ya, dan logikanya jg dipersimpel. coba tes bandingkan dgn yg sebelumnya. liat mana yg lebih akurat.

**Comment by sinung21** [comment]
2017-08-01 4:43 GMT+07:00 Fruitfella <notifications@github.com>:

**Comment by sinung21** [comment]
cocok buat digit macth mas

**Comment by sinung21** [comment]
Di email ok...jd LDP di ganti prediksi smua yh mas

Pada tanggal 1 Agt 2017 04:45, "hery priawan" <herypriawan9@gmail.com>
menulis:

**Comment by AndReWneSia62** [comment]
boleh minta BOT nya itu master
