### ISSUE TITLE
rule tick point

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#46]
saya ada rule @Fruitfella begini rule nya :Dia hanya akan open posisi membaca pergerakan tic di jarak tertentu untuk mengambil open follow trend atau reversal yg kita tentukan untuk rata rata trend saat ini 
Misal rise di point 25 kemudian fall di point 18 serta rise kembali di point 21 maka trend indikasi 70% open posisi Fall atau dow trend strong

**Comment by Fruitfella** [comment]
gak mudeng aq. kurang jelas

**Comment by sinung21** [comment]
![ice_screenshot_20170801-040741](https://user-images.githubusercontent.com/28952744/28798612-3d3dc7e4-766f-11e7-98cc-5cd9a60e5579.png)

**Comment by sinung21** [comment]
itu ma s..klo ada yg salah dgn bot itu,,tdk bsa run

**Comment by sinung21** [comment]
ini bot nya ada yang salh gak mas?


2017-07-31 17:54 GMT+07:00 Fruitfella <notifications@github.com>:

**Comment by Fruitfella** [comment]
gak jelas.
itu POINT isinya apa?
coba dijelaskan lebih detil logika analisa dan OP nya

**Comment by sinung21** [comment]
jadi bot itu akan melakukan open di pergerakan tik di jarak tertentu untuk
mengambil open baik follow dan reversal.

2017-08-01 5:00 GMT+07:00 Fruitfella <notifications@github.com>:

**Comment by Fruitfella** [comment]
Masih gak nyambung aq...
maksud q tolong dijelaskan "step by step" proses analisa/strateginya. trus apa aja yg dihitung.
"step by step" apa yg dilihat/dibaca bot, apa yg dihitung bot, apa yg dikerjakan bot.
Karna strategimu ini aq belom pernah denger jd gak punya gambaran sama sekali.

**Comment by sinung21** [comment]
misal saat di poin 25 bot itu akan rise dan kemudia fall di poin 18 jadi sisitem y fractal tik mas.

**Comment by sinung21** [comment]
![ice_screenshot_20170801-061005](https://user-images.githubusercontent.com/28952744/28802332-36783faa-7680-11e7-9dcc-4a2e2d1d80b7.png)

coba perhatikan bot ini gak bisa run untuk Rf

**Comment by ubanemas** [comment]
maaf mas sinung21, mungkin mas Fruitfella butuh detailnya, misal dia purchase di point 25 dan 18, maksutnya itu point apa tick ke 25 dan 18 kalau point, nah point yang anda maksud itu point dari mana? (dari perhitungan yg bagaimana?), kalau tick ke 25 dia purchase dan menghitung mundur kemudian di tick ke 18 dia purchase lagi jarak dari 25 ke 18 hanya 7 detik atau 3,5 tick sepertinya robot tdk bisa eksekusi krn masih ada transaksi berjalan mas Fruitfella mohon koreksi :)

**Comment by sinung21** [comment]
iya gt maksud q mas

**Comment by Fruitfella** [comment]
aq gak paham @sinung21 , strateginya kurang jelas, kalo yg aq tangkap dr gambar dan penjelasannmu, kemungkinan skenarionya ada banyak, gak mungkinlah aq bikin semua, makanya aq minta penjelasan yg rinci/detil ❓ 
@ubanemas yg sampean sebut itu cuma salah satu kemungkinan skenario. kemungkinan laen misal naek 25 pips turun 18 pips, masing2 dalam 1 tick. atau bisa jg dalam beberapa tick. atau naek 25 tiks turun 18 ticks. dan masih banyak lg. makanya aq bingung 😕 btw dari tick 25 ke tick 18 ada 7 tick bukan 7 detik, jd bisalah pas2an utk purchase durasi 5 ticks yg prosesnya makan 6 ticks.

**Comment by sinung21** [comment]
tlng bikin yang mas tau aj @Fruitfella

**Comment by ubanemas** [comment]
Owh iya tick ya knp aku mikirnya Jadi detik:), bisa klo tick, Cuman bener harus dikerucutkan lagi maunya yg gmn, apakah kemungkinan yg ta sampaikan diatas? Klo iya nah waktu tick ke 25 dia purchase berdasarkan apa? Harus diperjelas:)

**Comment by sinung21** [comment]
[binary-bot.sinung21-3.zip](https://github.com/Fruitfella/ROBOT-binary/files/1201643/binary-bot.sinung21-3.zip)
