### ISSUE TITLE
tehnik analisa LDP balok hijau

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#47]
Rule nya gini yg di jadikan ldp adalah angka yg berada dibalok ijo tunggu sampai balok td berubah jd putih atau sdh berpindah ke balok angka lain hitung 3 atau 5 tick op differ

**Comment by Fruitfella** [comment]
pending dulu, lg sibuk 😛

**Comment by Fruitfella** [comment]
Aq udah pernah upload Last Digit Analyzer di #35 
balok ijo= most frequent LD
balok merah= least frequent LD
