### ISSUE TITLE
Candle above below 75%

### ISSUE THREAD

**Issue by muroyal** [Fruitfella/ROBOT-binary#482]
How to calculate next candle status open above 75% and below 75$ of previous candle.

Kindly provide code for it.

If the new candle open above 75% or open above candle Buy Call
If the candle open below 75% or open below candle Buy Put.

Trade should open immediately on candle open after candle open above 75% of previous candle or below 75 % of previous candle (above > 75% or Below <75%) Continue for 55 Seconds) and verify condition on next candle open.

Thanks
Muroyal.

**Comment by trident2005** [comment]
You could place a graphic explanation of your approach, a drawing or something similar

**Comment by muroyal** [comment]
1) calculate previous candle open close price. 
2)if next new candle open previous candles above 75%  or above previous candle then BUY Call. 

3)If next new candle open below 75% of previous candle or below previous candle then BUY PUT. 

I have marked the candle open close example in image. 



![image](https://user-images.githubusercontent.com/32416314/71495084-f9779280-2871-11ea-845a-255f9ec4bd5f.png)

**Comment by trident2005** [comment]
Excuse me, what would be the meaning of programming that? Usually a new candle opens below or above 75% of the previous candle, otherwise there would have to be a huge GAP, that usually happens in 1 minute graphics

**Comment by muroyal** [comment]
I mean not 75% of GAP between previous candle. 

Next open price should open previous candle price 75% above for calls or below 25% for puts or open above previous close price or below previous close price.

**Comment by trident2005** [comment]
Sorry men, very bad english redaction

"Next open price should open previous candle price 75% above for calls or below..."        ?????????????????????????????????

Write better or make a better graph of what you want to do

**Comment by muroyal** [comment]
What u understood is right

"Next open price should open previous candle price 75% above for calls or below 25% puts..."
