### ISSUE TITLE
Thanks for the help! Your code is proftable!

### ISSUE THREAD

**Issue by unzer** [Fruitfella/ROBOT-binary#5]
Hi @Fruitfella 
Your last code is excellent! I made in almost 30' 18wins x 9wins!!!
Tks a lot!

**Comment by Fruitfella** [comment]
congrats for ur success in creating ur very own profitable bot!
btw, u need to test ur bot in a long run, like 5-6 hours, to know whether ur bot is really profitable or not, how much the risks, how much the minimum capital u need to run it, when the best time to trade with it and when u shouldnt.
good luck and have a nice day!
