### ISSUE TITLE
Help Bot Binary EMA 365 Periods

### ISSUE THREAD

**Issue by EulerBelfort** [Fruitfella/ROBOT-binary#503]
Help me

Hello guys, I'm creating a binary robot, but I'm having trouble making entries every time the price crosses a film with an average of 365, can someone help me, it does when it crosses up, but it doesn't identify or the step down is passing only call entries, if anyone can help me.

**Comment by ZDEGLET** [comment]
среднее значение чего 365

**Comment by EulerBelfort** [comment]
This Movie Average EMA365 Periods

Every time the price crosses the 365-period moving average the robot makes an entry, if it crosses up the entry is called and if it crosses down the entry is sell. understood?

**Comment by EulerBelfort** [comment]
fechado por falta de colaboradores
