### ISSUE TITLE
modal pake tanda koma bukan martiangle

### ISSUE THREAD

**Issue by aldiblackcat** [Fruitfella/ROBOT-binary#507]
tolong di bantu teman-teman semua, bagaimana agar modal bisa di setting menggunakan tanda koma ";" bukan menggunakan perkalian martiangle.
semisal saya ingin jalankan bot modal = 0.35,0.35,0.40,0.40
jadi apabila transaksi gagal di 0.35 akan lanjut ke 0.35 dan lanjut ke 0.40 dan lanjut ke 0.40 dan lanjut kembali lagi ke 0.35 dan berputar disekitaran itu saja.

apabila ada yang bisa bantu tolong posting di sini atau kirimkan file .xml ke email saya binarycobablackcat1 @ gmail . com
terimakasih semoga ilmu yang di share bermanfaat dan penuh berkah.  :)

**Comment by JenggotSantuy** [comment]
Jika sudah punya bot share aja
Insya Allah dibantu sesuai keinginan diatas

**Comment by cunk888** [comment]
Ada kontak wa? Biar saya bantu

**Comment by aldiblackcat** [comment]
085248578898

Dikirim dari Yahoo Mail di Android 
 
  Pada Sel, 25 Feb 2020 pada 23:48, cunk888<notifications@github.com> menulis:   
Ada kontak wa? Biar saya bantu

**Comment by aldiblackcat** [comment]
> Jika sudah punya bot share aja
> Insya Allah dibantu sesuai keinginan diatas

logikanya sederhana saja pak, digit diffrent walaupun botnya bagus perbandingan menangnya paling banyak 30:1, malahan kebanyak 10:1.
jadi kenapa tidak dibalik saja jadi digit match, klo modal bisa diatur semuanya jadi mudah.

**Comment by aldiblackcat** [comment]
> Ada kontak wa? Biar saya bantu

wa saya : +6285248578899
terimakasih banyak pak mau membantu saya, semoga bapak juga mudah dibantu orang dalam urusan apapun.

**Comment by ZDEGLET** [comment]
Я МОГУ ЭТО СДЕЛАТЬ!!! КИДАЙ РОБОТА НА ПОЧТУ
с пометкой 0.35 0.35 0.40 0.40
zdeglet@gmail.com

**Comment by cunk888** [comment]
Saya sudh chat tpi malah invite

**Comment by cunk888** [comment]
[Help.txt](https://github.com/Fruitfella/ROBOT-binary/files/4257109/Help.txt)
Ganti ke xml

**Comment by cunk888** [comment]
> > Ada kontak wa? Biar saya bantu
> 
> wa saya : +6285248578899
> terimakasih banyak pak mau membantu saya, semoga bapak juga mudah dibantu orang dalam urusan apapun.

Trimaksihhh

**Comment by aldiblackcat** [comment]
terimakasih banyak pak
