### ISSUE TITLE
bot bisa profit 

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#51]
@Fruitfella bisa tolong  biar bot ini bekerja dengan benar dan profit

[binary-bot.sinung21-3.zip](https://github.com/Fruitfella/ROBOT-binary/files/1201640/binary-bot.sinung21-3.zip)

**Comment by Fruitfella** [comment]
Maksudnya "bekerja dengan benar" itu apa?
Apa bot ini gak jalan? atau jalan tapi gak sesuai strategi? atau jalan sesuai strategi tapi gak profit?
Kalo aq liat, mestinya bot ini jalan, meskipun ada beberapa Logic block di tempat yg sebetulnya bisa dibuat tanpa Logic block tapi gak ada masalah, masih dalam kemampuan browser utk memproses.
Kalo botnya gak sesuai strategi ya aq gak bisa apa2, la wong strateginya apa aja aq gak tau.
Kalo botnya jalan sesuai strategi tapi gak profit ya tinggal ganti strategi _Lol_

note: pemakaian reverseMe di bot itu sangat konyol. Kata trader pro "Kalau strategimu selalu loss dan tdk pernah win, maka perlu dikaji ulang dan dirubah, bukan direverse"
