### ISSUE TITLE
A little help plz

### ISSUE THREAD

**Issue by Livandos** [Fruitfella/ROBOT-binary#514]
Hi guys , how to make а bot not trade selected time example 30s after loss 
Thanks.

**Comment by JenggotSantuy** [comment]
Like this
![Screenshot_20200306_052043](https://user-images.githubusercontent.com/61324577/76031565-81f96a00-5f6a-11ea-8957-e46444787fac.png)

**Comment by Livandos** [comment]
yes thanks
