### ISSUE TITLE
Koreksi setelah logika ditemukan

### ISSUE THREAD

**Issue by Skatezboy** [Fruitfella/ROBOT-binary#52]
nuhun mas, mengacu pada trend direction di #35 apakah bisa setelah formulanya ketemu, apakah bisa dibuat menunnggu (koreksi) 2 tick selanjutnya, misal formula "trend is up" ketemu, kemudian menunggu 2 tick berikutnya , jika 2 tick berikutnya berkali-kali down maka purchase dilakukan?

**Comment by Fruitfella** [comment]
bisa2 aja. karna arah trend kan kontinyu, bukan cuma sekejap lalu hilang. asal bukan period kecil pada trend tick.

**Comment by Skatezboy** [comment]
![capture](https://user-images.githubusercontent.com/7279426/29000447-4149d74a-7a95-11e7-81c0-dfddda619864.JPG)

apakah seperti ini mas? mohon dibantu

**Comment by Fruitfella** [comment]
ya bisa gitu. cuma **`Direction is Fall`** itu artinya turun 1 tick, kalo mau 2 tick ya buat perbandingan antara tick1, tick2 dan tick3.

**Comment by Skatezboy** [comment]
![test](https://user-images.githubusercontent.com/7279426/29000702-f0aac8ea-7a9d-11e7-90c0-2153afc1c407.JPG)
gini ta mas?maaf ngerepoti sampean

**Comment by Fruitfella** [comment]
ya, gitu bisa.
gambar sampean itu artinya : Kalo trend naik kemudian turun 2 tick, OP lower.
