### ISSUE TITLE
 Is it possible to open two in the time of 1 M?

### ISSUE THREAD

**Issue by fasinalves** [Fruitfella/ROBOT-binary#53]
THAT STRATEGY WORKS VERY WELL IN ANOTHER PLATFORM BUT IN BINARY I HAVE NOT SEEN THIS POSSIBILITY.
MAKING A CALL PURCHASE ON THE HIGH AND PUT CANDLE (THE PRICE KEPT IN THE MIDDLE AND GAIN IS FANTASTIC AND IF THE PRICE IS ABOVE OR DOWN BY CALL OR PUT, THE RISK OF LOSS IS LOW (ORDER OF $ 1 EACH)

![whatsapp image 2017-08-07 at 23 02 25 1](https://user-images.githubusercontent.com/29154824/29068954-3c9cf706-7c0f-11e7-95a0-e7588c5b7769.jpg)

![bomm](https://user-images.githubusercontent.com/29154824/29069799-d8a3b6d2-7c12-11e7-8176-68375ba5699f.jpg)

**Comment by Fruitfella** [comment]
I dont really get what you mean, my friend.
but, if you're asking about "to purchase both rise and fall simultaneously", then the answer is NO. its impossible to do that with the current binary bot.
well, there is a trick to it, but i dont recommend you to do that.
the trick is : simply run 2 bots with the same strategy simultaneously, 1 will only purchase rise and the other one purchase fall.

**Comment by fasinalves** [comment]
I KNOW THAT SYSTEM OF USING 2 BOT

**Comment by fasinalves** [comment]
MAKE A TEST OF THAT SYSTEM IN iqoption

**Comment by fasinalves** [comment]
Hello !!! Sorry for the delay !!!
yes but on the IQOPTION platform not on BINARY.com<http://BINARY.com>

Enviado do meu iPhone

Em 17 de set de 2017, às 07:26, Fruitfella <notifications@github.com<mailto:notifications@github.com>> escreveu:


Closed #53<https://github.com/Fruitfella/ROBOT-binary/issues/53>.
