### ISSUE TITLE
PLEASE CHECK IF YOU HAVE AN ERROR

### ISSUE THREAD

**Issue by fasinalves** [Fruitfella/ROBOT-binary#54]
OLA Fruitfella 
IN HIS TICK TREND POSITION IT DID NOT WORK AND I HAVE BEEN CHANGING AND WORKING.

POSSIBLE TO MAKE TICK FUNCTION WITH 3 SMOOTH MEDIUM MOVEL?
YOUR MOBILE HALF WORKS WELL I AM TRYING TO COMBINE IT WITH ANOTHER VESTIVE STRATEGY.

![4444444](https://user-images.githubusercontent.com/29154824/29074279-14cfa906-7c25-11e7-8c47-b291cb6fe2e7.png)

![333333](https://user-images.githubusercontent.com/29154824/29074011-2b009236-7c24-11e7-8d01-a0b8ff8bb424.png)

**Comment by Fruitfella** [comment]
thanks for noticing that, Fabio. :)
