### ISSUE TITLE
BOT DIGIT DIFFERT

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#57]
@Fruitfella BISA tolong saya bikin bot digit differt anti level 2...dengan  strategi awal op dari digit differt kemudian op ke digit macth setelah 5 kali differt.

**Comment by Fruitfella** [comment]
"differt anti level 2" itu apa?
setelah 5x diff trus match, habis itu diff lg atau tunggu 5x match baru diff?

**Comment by sinung21** [comment]
Kena level 2 begini...awal op loss ..yg kedua jg loss bgtu...ya setelah 5x op difert bot akn op macth sekali...baru op differt lg@fruitfella

**Comment by Fruitfella** [comment]
op1=diff
op2=diff
op3=diff
op4=diff
op5=diff
op6=match
op7=diff
op8=diff
op9=diff
op10=diff
op11=diff
op12=match

gitu?
trus yg op awal dan kedua loss itu apanya?

**Comment by sinung21** [comment]
saya seringnya menggunakan bot digit difert selalu terkena los berturut turut 2x @fruitfella...jdi sy pengin bot percampuran antara digit differt dan macth

**Comment by Fruitfella** [comment]
ini 5x diff trus 1x match
![capture](https://user-images.githubusercontent.com/26277327/29171994-b4d6d0a2-7e08-11e7-9a6f-e25bf15424a7.png)

**Comment by sinung21** [comment]
Ok terimakasih @fruitfella q cb rakit n play
