### ISSUE TITLE
notifikasii

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#58]
mas bisa tlng bikinkan bot analisa pola 4 tick dengan periode point nya

**Comment by Fruitfella** [comment]
bisa dijelasin lebih rinci? step stepnya?

**Comment by sinung21** [comment]
Seting V100...dgn analisa tik 4...yg kyak gini      UP DOwn Up down.  Periode point 15... mode reversal.

**Comment by Fruitfella** [comment]
kurang jelas.
kondisi OP?
kapan harus OP rise?
kapan harus OP fall?

**Comment by sinung21** [comment]
maksud saya bot notifikasi analisa tik mas...up  down  up down= jadi 4 analisa

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/29212147-298a3330-7ec7-11e7-8d16-466d4a024de3.png)

**Comment by sinung21** [comment]
![20786547_330007250758038_1419007267_n](https://user-images.githubusercontent.com/28952744/29231168-65be62ce-7f10-11e7-982f-e425e5293af0.jpg) seperti itu mas
