### ISSUE TITLE
bot touch

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#64]
mas bisa tolong buatkan bot touch dengan auto trend. dengan profit 35%...jadi saat trend naik bot op dengan barier +. dan saat trend turun  bot op dengan barier -. terimakasih

**Comment by ubanemas** [comment]
strateginya gimana brow?, klo untuk konfirmasi trend kan sudah ada diposting sama mas nya, tinggal kreatifitas kita aja......

**Comment by Fruitfella** [comment]
bray @sinung21 , kalo nanya itu mbok ya yg jelas to, utk bikin bot itu rule nya harus jelas dan tepat, kalo gak, bingung aq mau kasih perintah apa ke botnya. :man_facepalming: 

@ubanemas temen kita yg satu ini sering nanya tapi kebanyakan permintaanya terlalu abstrak dan kurang detil, seolah2 aq pasti tau maksudnya :rofl:

**Comment by ubanemas** [comment]
@sinung21 bisa pake strategi yg pernah ta request... pake tf 15,5,1 klo searah dia purchase touch...dan masih ta pake sampe skrg....silahkan di cari
