### ISSUE TITLE
Help on the Strategy

### ISSUE THREAD

**Issue by mnaseem01** [Fruitfella/ROBOT-binary#69]
@Fruitfella ,
How i can convert below code on the block code. Please help
try:
                #First Candle
                first_candle_time = api.candles.first_candle.candle_time
                first_candle_open = api.candles.first_candle.candle_open
                first_candle_close = api.candles.first_candle.candle_close
                first_candle_high = api.candles.first_candle.candle_high
                first_candle_low = api.candles.first_candle.candle_low
            
                #Second Candle
                second_candle_time = api.candles.second_candle.candle_time
                second_candle_open = api.candles.second_candle.candle_open
                second_candle_close = api.candles.second_candle.candle_close
                second_candle_high = api.candles.second_candle.candle_high
                second_candle_low = api.candles.second_candle.candle_low
            
                #Current Candle
                current_candle_time = api.candles.current_candle.candle_time
                current_candle_open = api.candles.current_candle.candle_open
                current_candle_close = api.candles.current_candle.candle_close
                current_candle_high = api.candles.current_candle.candle_high
                current_candle_low = api.candles.current_candle.candle_low

                #Read trend and make decision
                #TBH Pattern
                if (first_candle_high == second_candle_high):
                    #TBH Rise Pattern
                    if (current_candle_high > second_candle_high):
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        api.buy(amt, 1, "turbo", "call")
                        print ("TBH Rise: CALL $" + str(amt))
                        time.sleep(5)
                        loss_count += 1
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(25)
                    #TBH Drop Pattern
                    elif (current_candle_low < second_candle_low):
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        api.buy(amt, 1, "turbo", "put")
                        print ("TBH Drop: PUT $" + str(amt))
                        time.sleep(5)
                        loss_count += 1
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(25)
                    else:
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        print ("TBH Pattern is not strong enough...")
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(3)
                #TBL Pattern
                elif (first_candle_low == second_candle_low):
                    #TBL Rise Pattern
                    if (current_candle_low > second_candle_low):
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        api.buy(amt, 1, "turbo", "call")
                        print ("TBL Rise: CALL $" + str(amt))
                        time.sleep(5)
                        loss_count += 1
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(25)
                    #TBL Drop Pattern
                    elif (current_candle_low < second_candle_low):
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        api.buy(amt, 1, "turbo", "put")
                        print ("TBL Drop: PUT $" + str(amt))
                        time.sleep(5)
                        loss_count += 1
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(25)
                    else:
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        print ("TBL Pattern is not strong enough...")
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(3)
                #DBLHC (Low-High) Pattern
                elif (first_candle_low == second_candle_low):
                    if (second_candle_close > first_candle_low):
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        api.buy(amt, 1, "turbo", "call")
                        print ("DBLHC (Low-High): CALL $" + str(amt))
                        time.sleep(5)
                        loss_count += 1
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(25)
                    else:
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        print ("DBLHC (Low-High) Pattern is not strong enough...")
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(3)
                #DBHLC (High-Low) Pattern
                elif (first_candle_high == second_candle_high):
                    if (second_candle_close < first_candle_low):
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        api.buy(amt, 1, "turbo", "put")
                        print ("DBHLC (High-Low): PUT $" + str(amt))
                        time.sleep(5)
                        loss_count += 1
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(25)
                    else:
                        print(str(api.timesync.expiration_datetime))
                        print(str(api.timesync.server_datetime))
                        print ("DBHLC Pattern is not strong enough...")
                        new_balance = api.profile.balance
                        print ("Balance: $" + str(new_balance))
                        time.sleep(3)
                #Unstable trend
                else :
                    print(str(api.timesync.expiration_datetime))
                    print(str(api.timesync.server_datetime))
                    print ("NO RISK TAKEN")
                    new_balance = api.profile.balance
                    print (new_balance)
                    time.sleep(3)
            except: 
                pass
            

            #End of if-else statement
            print ("====================")
            
        #End of loop

**Comment by Fruitfella** [comment]
woah woah dude! where did u get that? 😮 
fyi i'm not a coder, i have zero knowledge on programming language 😛 
the reasons why i can make bot.xml are because i'm good with logics, know a little english and very good with jigsaw puzzle and lego. of course amin and kovalov also help me a lot in understanding the binary bot.
i suggest u to ask a real programmer such as okovalov

**Comment by mnaseem01** [comment]
@Fruitfella , thanks i already converted to block codes.
