### ISSUE TITLE
 Is it possible to implement this

### ISSUE THREAD

**Issue by Daler4ik** [Fruitfella/ROBOT-binary#70]
Hi @Fruitfella, is it possible in a binary bot to make a bot that trades Pin-Bar?

![pin-bar1](https://user-images.githubusercontent.com/31123446/30104732-f202af16-930f-11e7-91b7-0c6f32bda15c.png)

**Comment by Fruitfella** [comment]
Hi @Daler4ik, sorry for the long wait :)
pinbar signal is very possible, u can use my <a href="https://github.com/Fruitfella/ROBOT-binary/issues/35">tool/function</a> for that.
this is an example for white pinbar
![capture](https://user-images.githubusercontent.com/26277327/30240122-d42fcc12-9594-11e7-8261-5d45e906ea33.png)

**Comment by Daler4ik** [comment]
Thank you so much @Fruitfella

**Comment by CorreiaMerchant** [comment]
@Fruitfella 

Para a opção Pinbar preto Put se altera somente (< e >) ?

**Comment by Fruitfella** [comment]
@CorreiaMerchant for black pinbar, just switch lower shadow with upper shadow.
