### ISSUE TITLE
Help Digit Odd/Even

### ISSUE THREAD

**Issue by valentino242** [Fruitfella/ROBOT-binary#75]
HI Om. Saya Andre dari Surabaya Need Ur Help.

Analisa setiap last digit per 5 tick
tick 1 even
tick 2 odd
tick 3 even
tick 4 even 
tick 5 odd --------------  odd ke 1

Apa bisa dibantu. Terimakasih Om.

**Comment by Fruitfella** [comment]
kurang jelas analisanya.

tick 1 even
tick 2 odd
tick 3 even
tick 4 even
tick 5 odd
tick 6 even
tick 7 odd
tick 8 even
tick 9 odd
tick 10 odd
tick 11 even
tick 12 odd
tick 13 odd
tick 14 even
tick 15 even 

kalo marketnya begini, trus gimana?

**Comment by valentino242** [comment]
Kalau Marketnya begitu terus seperti ilustrasi yang Om berikan tidak akan OP Om. Tapi memang tujuan untuk itu Om sebagai filter . Berdasarkan test seharian running BOT tanpa filter rata" level martingle yang terdalam di level 8 kalau dengan filter ini jadi 5 level . Jadi pointnya cuman nunggu Loss 3x dulu sebagai acuan indikatornya baru OP.

**Comment by Fruitfella** [comment]
artinya hanya OP ketika tick 5, 10 dan 15 = odd?

**Comment by valentino242** [comment]
Benar Om

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/30519279-40654eb6-9bbc-11e7-9c5a-9393224f99ef.png)
[digit-odd-even.zip](https://github.com/Fruitfella/ROBOT-binary/files/1308944/digit-odd-even.zip)

**Comment by valentino242** [comment]
Siap Om. Saya test dulu terimakasih banyak

**Comment by valentino242** [comment]
![test](https://user-images.githubusercontent.com/31639222/30519842-33c44866-9bca-11e7-850c-086f5fa722f2.png)

**Comment by Fruitfella** [comment]
sip! 👍

**Comment by valentino242** [comment]
HI Om balik lagi ... Maaf merepotkan lagi .

Kalau dibuat Topologi seperti dibawah ini gmn ya Om Fruitfella:
Analisa Digit --- Loss ----OP  Martingale langsung pada tick berikutnya**(tanpa Analisa digit lagi)**  sampai Profit / Menyentuh Level Martingale yang dikehendaki ---- Jika kondisi terpenuhi maka Reset ke Awal Analisa digit.

" Jika Loss Analisa digitnya di Skip Om sampai memenuhi syarat diatas. "

Kalau yg sekarang : Analisa Digit ----Loss ---- Analisa Digit dan Martingale Level 1---- Loss Analisa Digit lagi dan Martingale Level 2 ----- Profit ----- Analisa Digit .

Makasih Om

**Comment by valentino242** [comment]
Om bisa share Email or WA tks

**Comment by Fruitfella** [comment]
???
itu alo loss, kalo win trus gimana?
e-mail : rudika.fx@gmail.com

**Comment by valentino242** [comment]
Ok siap

**Comment by rubluzz** [comment]
> ![capturar](https://user-images.githubusercontent.com/26277327/30519279-40654eb6-9bbc-11e7-9c5a-9393224f99ef.png)
> [digit-odd-even.zip](https://github.com/Fruitfella/ROBOT-binary/files/1308944/digit-odd-even.zip)

olá. nao consigo colocar para funcionar o bot. pode me ajudar? sou iniciante
