### ISSUE TITLE
Mohon petunjuk bot binary digit Even

### ISSUE THREAD

**Issue by rosidanwar** [Fruitfella/ROBOT-binary#76]
strategi : 
apabila spot harga V25 = xxxx.777
pada saat angka di belakang titik .777 lalu purcase even

**Comment by mnaseem01** [comment]
@rosidanwar , please explain more in details. i think this number comes very rare, so i feel this is not good strategy, to wait until come this number after 1 hr.

**Comment by Fruitfella** [comment]
@rosidanwar, kurang jelas.
xxxxx.586
xxxxx.038
xxxxx.777 <----- 1
xxxxx.264
xxxxx.033
xxxxx.790
xxxxx.777 <----- 2

OP di 1 atau di 2?

**Comment by sinung21** [comment]
op di 2

**Comment by Fruitfella** [comment]
this issue were closed because in "unclear" status for too long.
