### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Daler4ik** [Fruitfella/ROBOT-binary#78]
Hi @Fruitfella, how are you?
I need your help. Please tell me how I can do this: if the last tick, for example, 10765.(85), and then the last tick 10765.(90), buy.

**Comment by shappy88** [comment]
Bro , i am newbie ..i just register it now ..
i dnt knw coding very much..
i was searching for all kind of answer and found u replied most of it ..
so i thought to look at ur profile ..
i was there to knw what is what in the github ..
if u knw coding i have succesful strategies .. which are not 100% but
close to it..
thus i need a bot for the lenghty work , i tried but i didnt get that
much of how to make it..
If u can help , i can tel u my strategies which i came up with my ownn..
Cheers<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #D3D4DE;">
	<tr>
        <td style="width: 55px; padding-top: 13px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 12px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virus-free. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a>
		</td>
	</tr>
</table><a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1"
height="1"></a></div>

**Comment by Daler4ik** [comment]
@shappy88 I'm sorry, I did not understand you. Do you want me to share a strategy with you?

**Comment by shappy88** [comment]
NO  bro ...
 I have some strategies .. which yields a good result.
but can't-do manually as it has to do many times.
So i was trying to make a bot for it ..
but didnt understand the coding part ..
I like to share some strategies with you , if you can make the bot for it..
SImple but effective strategies..
Can u make it ?

**Comment by Daler4ik** [comment]
@shappy88 Probably yes. I have a little experience. Write to me on the mail

**Comment by Daler4ik** [comment]
@shappy ir_47@yahoo.com

**Comment by Daler4ik** [comment]
@shappy88 ir_47@yahoo.com

**Comment by mnaseem01** [comment]
@shappy88 You can share with me also, i can help to write bot. mnaseem81@gmail.com

**Comment by Fruitfella** [comment]
@Daler4ik 
xxxxx.14
xxxxx.85 <-
xxxxx.90 <----- (1)
xxxxx.73
xxxxx.02
xxxxx.56
xxxxx.85 <-
xxxxx.33
xxxxx.25
xxxxx.90 <------ (2)
are both (1) and (2) okay? or its just (1) ?

***
@shappy88 ❓

**Comment by Daler4ik** [comment]
Many thanks that answered @Fruitfella. You misunderstood me, forgive me for my English. I mean that 

if,  for example: 
XXXXX.25 
XXXXX.30 purchase, 

if: 
XXXXX.14 
XXXXX.19 purchase, 

if: 
XXXXX.67 
XXXXX.72 purchase. 

When the numbers XXXXX."YY" rises above 5, purchase.

**Comment by Daler4ik** [comment]
By the way, @Fruitfella can you give me your contact details? For example Facebook or an email address

**Comment by Fruitfella** [comment]
email : rudika.fx@gmail.com

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/30773122-7d6c79b0-a094-11e7-9a7f-1966054c79ad.png)

**Comment by Daler4ik** [comment]
Thank you @Fruitfella.
I will write to you soon about one strategy. I do not have the opportunity to implement it in Binary Bot, I think you will help me) again many thanks

**Comment by tiendienhe** [comment]
@Fruitfella I tried to contact you but could not. I am very interested in a robot you have
If you are not busy you can mail me
tiendien410@gmail.com
thank
