### ISSUE TITLE
Bot yang tidak di share

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#85]
Mas @fruitfella  bisa tlng ksih tau rule bot nya yg gk di share...itu

**Comment by sinung21** [comment]
Rule logika bot follow trend

**Comment by Fruitfella** [comment]
waduh. namanya jg gak di share. itu artinya gak bakal dikasih tau siapa2 😛 itu rahasia perusahaan 😆

**Comment by sinung21** [comment]
Rule y aj maz.please
