### ISSUE TITLE
BANTU buat bot ini

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#86]
![22016844_128479481214552_1420935539_o](https://user-images.githubusercontent.com/28952744/30787320-e98c9712-a1af-11e7-8ff1-563eccb09f1b.png)
 

@Fruitfella  bisa tolong bikin bot dengan gambar ini...garis MA menembus dari lower Bb ke upper Bb.. OP RISE....dan MA menembus BB Upper ke BB lower maka OP FALL... Disertai dengan SMA SHIFT + untuk menentukan candle akan kemana.

**Comment by Daler4ik** [comment]
I do not know what you mean, but it can help.
(Sorry for my English)
![screenshot_4](https://user-images.githubusercontent.com/31123446/30828156-2d7a2f88-a256-11e7-8070-c2e42bd0a3c0.png)

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/31041505-dc184f94-a5c0-11e7-92dc-3070854a7c65.png)
