### ISSUE TITLE
BUTUH PERTOLONGAN

### ISSUE THREAD

**Issue by sinung21** [Fruitfella/ROBOT-binary#87]
@Fruitfella  bisa tolong agar bot ini bisa OP dua arah..?
[Angka-kembar-2 (1).zip](https://github.com/Fruitfella/ROBOT-binary/files/1331010/Angka-kembar-2.1.zip)

**Comment by Fruitfella** [comment]
bot mu kurang jelas strategynya.
aq gak tau kondisi purchasenya, jd gak bisa bantu edit :P
