### ISSUE TITLE
Suggestion For Selling Bots

### ISSUE THREAD

**Issue by Agentsbu** [Fruitfella/ROBOT-binary#90]
Hi guys i have a suggestion. I have had a good experience with fruitfella. I have tested so many bots here and some of them i realised are worth selling. Why can't Fruitfella create a forum where we can sell bots to each other ? For example: if someone wants to sell a bot they send it to Fruitfella for verification and testing and then after testing Fruitfella gives a review and price how much it's worth ? Think about it @Fruitfella

**Comment by Fruitfella** [comment]
😄 you flattered me @Agentsbu 
i'm very happy for your trust, though i dont think i've done anything worth such trust.
its too bad that i cant help you with this 'bot selling'. i dont even have time to trade with my trefollbot (thats why i postponed it) and can only help you guys (in creating bot) on weekends. my workloads are too much for me that i only get few spare times. you can blame my boss for that *lol*.
even so, i dont mind if any of you decide to introduce/promote your bot here. and if its only to check the bot's logic, confirm whether the bot works according to the strategy or not, and how risky it is, i think i could do that (every weekends). 
for now its impossible for me to make a serious review and judge the bot's potentials.
well, maybe later when my boss have mercy on me and decide to lessen my workloads (and increase my salary *lol*) ?

btw, if you want to sell your bot, i heard that binary(dot)com shop offer some assistances in bot selling.

**Comment by Agentsbu** [comment]
Lol @fruitfella. Thanks a lot will make a plan.you can close.

**Comment by Agentsbu** [comment]
It's ok then but please lets make it happen, starting right now. Also someone can request to buy a special bot and state how much they have.

**Comment by Agentsbu** [comment]
Will submit a real request to show example.
