### ISSUE TITLE
Problem with EMA Trend

### ISSUE THREAD

**Issue by xremmy** [Fruitfella/ROBOT-binary#99]
Hi Fruifella, 
Thanks for all your help so far. 
Like Oliver Twist, I'm back again. I am using your EMA trend tool but i think i have messed up the blocks arrangement
The Ema's i believe is 6,14 and 26. When i plot this on a chart, there are times when a strong trend is in place but the BOT does not place trades. 
Whenever you are free, would appreciate if you can help check it out.
Thanks
![fruitfella question 3](https://user-images.githubusercontent.com/25975068/31583198-3c438054-b18e-11e7-86ea-542db1c16c97.JPG)

**Comment by Fruitfella** [comment]
that "smooth" blocks are experimental. still has some problems and isn't fixed yet.
maybe i'll fix later when i have more free times or when i really have the need to use it ;P
as for now, i suggest you not to use it unless you want to do your own experiments with it and help me find the problem. :)

**Comment by xremmy** [comment]
Thanks Fruitfella. 
I will just replace it with the ema indicators. Will try and run the experiments as suggested, i just noticed that it takes trades when the ema's are not parallel.
